### ISSUE TITLE
Better error on wrong URL

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal#102]
GET https://apps.keboola.com/apps/keboola.ex-hubspot

produces
`{
  "message": "Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=ey-...snip...EA--VA"
}`

**Comment by JakubMatejka** [comment]
Hm, to je obecně docela problém. Musel bych v API Gateway nadefinovat resource, že na `/apps/*` má vracet 404 (což teda udělám, to bude asi pomerně častej překlep), ale takhle by se to muselo vyjmenovat pro všechny možný varianty.

**Comment by odinuv** [comment]
Chapu, no me se tohle za posledni tyden stalo asi 6x, takze by to asi stalo za uvahu

**Comment by JakubMatejka** [comment]
Jej, sorry, tak to nejde. Nedošlo mi, že když je definovaná routa `apps/{vendor}/{app}`, tak už nejde definovat `apps/{anything}`. Budeme muset počkat, až to v API Gateway půjde pořešit nějak rozumněji ;o/
