### ISSUE TITLE
Perform DB migration before deploying API

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#103]
Migrace až po zveřejnění nový verze může způsobit, že se spustí nějaký API call ještě před dokončením migrace

**Comment by Halama** [comment]
možná stačí o tom vědět a posílat migrace v releasu dopředu?

**Comment by JakubMatejka** [comment]
No, zatím to tak dělám ;o)

**Comment by JakubMatejka** [comment]
Popsal jsem to do readme a zatím zavírám.
