### ISSUE TITLE
undocumented uiOptions

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#105]
je tam dost uiOptions, který nejsou vůbec zdokumentovaný, ani v seznamu
nechám na zvážení, jestli to dokumentovat, ale i když budeme mít UI, tak imo by dokumentace API měla pokrejvat všechny možnosti

**Comment by ondrejhlavacek** [comment]
taky tam je špatně uvedený `tableOutput` etc, místo `genericDockerUI-tableOutput`

**Comment by JakubMatejka** [comment]
Jasně doplním, ale problém je, že sám nevím který tam můžou být, tady jich je jen pár: https://developers.keboola.com/extend/registration/#ui-options

**Comment by odinuv** [comment]
no k tomu jsou jeste `dataIn` a `dataOut` a to je vsecko ne?

**Comment by JakubMatejka** [comment]
Na oauth je taky něco, myslím(?). BTW. je dataIn a dataOut k něčemu? Nemají dataIn všechny extraktory a dataOut všechny writery? (nebo ten flag ukazuje něco jinýho?)

**Comment by ondrejhlavacek** [comment]
kompletní popis všech flagů je tady - https://sites.google.com/a/keboola.com/devel/kbc/ui/component-flags

**Comment by odinuv** [comment]
no UI to ukazuje podle toho flagu, a treba geocoding augmentation je extractor a stejne by mel mit dataout

**Comment by ondrejhlavacek** [comment]
když na to koukám, stálo by to za sjednocení - ty názvy jsou matoucí, vznikaly nahodile, podle potřeby, bez struktury a házely se všechny do jednoho pytle. 

bylo by asi dobrý je rozházet a přejmenovat, aby to dávalo logickej smysl z pohledu developer portálu, a v migračním skriptu to zase namapovat zpět

**Comment by odinuv** [comment]
tak excludeRun vubec nevim k cemu je :)

**Comment by ondrejhlavacek** [comment]
např `keboola.csv-import`
