### ISSUE TITLE
Allow call /apps/{app}

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#107]
Momentalne sa detail appky ziskava cez vendora:
`/apps/{vendor}/{app}`

t.j.: `/apps/keboola/keboola.ex-mongodb`

Chcel by som aby to slo priamo:
`/apps/{app}`

t.j.: `/apps/keboola.ex-mongodb`

---

Aby sa zachovala spatna kompatibilita, slo by imho spravit nieco taketo:

`/apps/{vendor-or-app}/{app}`

Novy sposob (poslem len jeden param), vtedy je to `app`:

![screenshot_2017-05-26_18-13-09](https://cloud.githubusercontent.com/assets/419849/26502924/fe425f64-423e-11e7-9f56-ebe9f5d51dd8.png)

Stary sposob, kvoli BC, poslem oba a je to `vendor` + `app`:

![screenshot_2017-05-26_18-14-57](https://cloud.githubusercontent.com/assets/419849/26502985/40f5c81e-423f-11e7-840c-5b81476fbee8.png)

**Comment by ujovlado** [comment]
Pripadne by ten stary req. mohol hodit `301 Moved Permanently`:

`/apps/keboola/keboola.ex-mongodb` -> `/apps/keboola.ex-mongodb`

Ale mozno sa s tym neoplati babrat a radsej spravit BC break :smile:

**Comment by JakubMatejka** [comment]
v Serverless to nakonfigurovat prostě nejde (možná protože je to přes CloudFormation?)
![slack - keboola tech 2017-05-26 21-18-23](https://cloud.githubusercontent.com/assets/215660/26509404/e32b64a4-4258-11e7-97b4-e19d792926a1.png)
Zkusil jsem opačný pořadí, tj. smazat `apps/{vendor}/{app}` a pak vytvořit nejdřív `apps/{app}` a potom `apps/{vendor}/{app}`, ale nepomohlo to. Nejspíš to bude fakt tím CloudFormationem ;o/

**Comment by JakubMatejka** [comment]
Done
