### ISSUE TITLE
Setup custom 404 for non-existing resources

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#109]
https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-api-gateway-enables-customization-of-error-responses/

**Comment by JakubMatejka** [comment]
Tak ještě budem muset počkat na podporu v Serverless

**Comment by JakubMatejka** [comment]
"Gateway Responses" zatím nejde nastavit v CF, viz. https://github.com/serverless/serverless/issues/3896

**Comment by sj00** [comment]
Gateway Responses is now added to CloudFormation.

[List](http://docs.aws.amazon.com/apigateway/latest/developerguide/customize-gateway-responses.html) of Gateway Response Types.

From cloud formation [docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-gatewayresponse.html), here's a snippet:

`resources:
  Resources:
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: MISSING_AUTHENTICATION_TOKEN
        RestApiId: 
          Ref: 'ApiGatewayRestApi' # Constant for serverless
        StatusCode: '401'`

**Comment by JakubMatejka** [comment]
Fixed in 8fbaa5ea50614807d9206fa73d45f6249e0a22f9
