### ISSUE TITLE
Add users waiting for confirmation to a list of vendor members

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#111]
Myslim, ze by sa hodilo v liste userov vracat aj tych, co este nie su potvrdeni.

Mam na mysli tento API call:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/list-users

Vendor api to dava takto:
```json
[
  {
    "email": "test@keboola.com",
    "name": "Test User",
    "description": ""
  }
]
```
Admin api:
```json
[
    {
        "email": "test@keboola.com",
        "name": "Test User",
        "vendors": ["keboola"],
        "description": "",
        "createdOn": "2016-08-10T19:02:46.361Z",
        "isEnabled": true,
        "status": "CONFIRMED",
    }
]
```

Myslim, ze to vendor API by mohlo tiez obsahovat `status` a `createdOn`

**Comment by JakubMatejka** [comment]
Ok, `createdOn`, `isEnabled` a `status` dodám (i když `createdOn` je datum registrace, ne přidání do vendora, tak jsem si nebyl jistej jestli to mají ostatní ve vendoru vědět, ale asi to není nic zásadního ;o) Jinak nepotvrzení uživatelé by tam měli být vidět už teď, žádný filtr na nich není

**Comment by ujovlado** [comment]
tak to `createdOn` asi byt nemusi, ak to nema relevantny vyznam :)

**Comment by ujovlado** [comment]
Ale ked som poslal request na pridanie sa do vendora, tak toho usera nevidim

**Comment by JakubMatejka** [comment]
Aha, tak to vidět není. Ten request není vlastně nikde uloženej, pošle se jen notifikace přes SNS. Ale asi by bylo lepší kdyby tam byl a mohl se schválit kliknutím v ui.

**Comment by ujovlado** [comment]
To, ze to pojde schvalit z UI moze byt dalsi task ... vsimol som si, ze tam treba kod, ktory prisiel na mail.

Skor som mal na mysli toto:
https://github.com/keboola/developer-portal/blob/8824961/lib/UserPool.js#L65 ... tam sa to odfiltruje ak sa nemylim

**Comment by ujovlado** [comment]
Ale na to spravim kludne dalsiu issue, nech sa to nemiesa.

**Comment by ujovlado** [comment]
V tomto asi doriesim len tie atributy

**Comment by JakubMatejka** [comment]
Kód je u pozvánky, ne když o připojení žádá sám uživatel (i když jsem přemýšlel, že bych tu žádost o připojení asi zrušil, nebo aspoň přesměroval notifikace ostatním userům vendora, teď chodí nám do Slacku).

Co chceš říct tím línkem sem https://github.com/keboola/developer-portal/blob/8824961/lib/UserPool.js#L65? ;o) `listUsers()` vrátí úplně všechny uživatele portálu (v Cognito bohužel nejde zatím při vyhledávání filtrovat u custom atributů ;o/)

**Comment by ujovlado** [comment]
Pridal som sa pod vendora, poslal som "Request to join a vendor.":
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/request-to-join-a-vendor

No v zozname userov, tohto uzivatela nevidim:
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/list-users

**Comment by JakubMatejka** [comment]
Ale vždyť jsem psal, že informace o tom, že se snažíš připojit k vendorovi se nikam neukládá (https://github.com/keboola/developer-portal/issues/111#issuecomment-308085508), tudíž nemám jak získat seznam "waiting" uživatelů. Odtud https://github.com/keboola/developer-portal/blob/8824961/lib/UserPool.js#L65 to nezjistím

**Comment by ujovlado** [comment]
Aha, tak uz rozumiem ... teda medzistav nie je ulozeny .... a tam sa mi to odfiltruje, lebo user este pri tom vendorovi nie je, jo. Tak toto asi zavrem, to pridanie atributov asi nema vyznam, ked toho usera stejne neuvidim :)

**Comment by JakubMatejka** [comment]
Jj. Ale můžem to tu nechat právě kvůli tomu, že bych to uložení mezistavu dodělal. (Pak by se dal request schvalovat právě i v ui.)

**Comment by ujovlado** [comment]
Dobre  :) ale nehori to
