### ISSUE TITLE
Get profile returns vendor's tmp id in vendors field

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#112]
Ked poslem req. na vytvorenie noveho vendora, tak po zavolani "get profile" dostavam vo fielde vendors aj temporary id toho vendora.

Example response:
```json
{
  ...
  "vendors": [
    "_v14975606633540.655563443767270"
  ],
  ...
}
```

Myslim, ze by to nemalo vracat nic, pokial nie som naozaj clenom vendore, resp. pokial nie je schvaleny.

**Comment by ujovlado** [comment]
Podobne by to nemuselo davat ani do tokenu.

**Comment by JakubMatejka** [comment]
Závisí na #111, informace o tom, že user má patřit do vendora po jeho schválení se bude muset ukládat někde bokem (v db)

**Comment by ujovlado** [comment]
Len pre potvrdenie. Pri niektrorych useroch este tuto info vidim (asi to pochadza z migracie). Nie je to pri volani user detail ale pri admin API calle na list vsetkych userov.

Mozem im teda toho "tmp vendora zmazat"?

Priklad
![screenshot_2017-08-17_18-17-42](https://user-images.githubusercontent.com/419849/29422403-630aac06-8378-11e7-88e5-a9239050fc9f.png)
