### ISSUE TITLE
can not reset password with already used unconfirmed email

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#113]
Vytvoril som si uzivatela ale nepotvrdil som ho cez konfirmacny link
Teraz po dlhsom case sa snazim vytvorit znova na rovnaky email ale dostavam hlasku user already exist, ked dam password reset tak to skonci aplikacnou chybou: 
```
{"name":"InvalidParameterException","message":"Cannot reset password for the user as there is no registered/verified email or phone_number"
```
https://keboola.slack.com/archives/C2LNXBT1P/p1497865155576245

**Comment by JakubMatejka** [comment]
A znovuposlání konfirmačního kódu nefunguje? http://docs.kebooladeveloperportal.apiary.io/#reference/0/auth/resend-confirmation-code

**Comment by ujovlado** [comment]
Mne to prave dalo application error (req. id `3e223850-793f-11e7-a7b9-290b0ea510ca`). Je to teda pri tom, ked sa snazim resetnut heslo pre usera, ktory nema confirmed email - t.j. pri logine hodilo `User is not confirmed.`

**Comment by ujovlado** [comment]
Aha, v slacku je teda "Cannot reset password for the user as there is no registered/verified email or phone_number"

**Comment by ujovlado** [comment]
Toto zabralo:

> A znovuposlání konfirmačního kódu nefunguje? http://docs.kebooladeveloperportal.apiary.io/#reference/0/auth/resend-confirmation-code

Kazdopadne, asi by to nemuselo hodit 500, ale skor nejaku 400
