### ISSUE TITLE
sending invitation to user that is already in vendor timed out

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#114]
api call: http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/invite-user-to-a-vendor

Fails on timeout if send invitation to the user that is already in the vendor. Should return a user error saying that user is already in the vendor.

**Comment by ujovlado** [comment]
![screenshot_2017-06-27_10-03-13](https://user-images.githubusercontent.com/419849/27577136-e386ac4e-5b1f-11e7-8216-52163a252272.png)

A toto je v response:
```json
{"message": "Endpoint request timed out"}
```

**Comment by ujovlado** [comment]
@JakubMatejka diky za fix, uz to netimeotuje, no teraz to vracia:

```json
{"message":"Unauthorized"}
```
Nemalo by to skor vratit 422 a nejaku hlasku, ze user uz v danom vendorovi je?

**Comment by ujovlado** [comment]
Pockat, zle som klikol ... staci teda aby to nevracalo "forbidden"
https://github.com/keboola/developer-portal/commit/7fe507c33a5b7c6a6c8aad1cd1fce4eb18b8c205

**Comment by ujovlado** [comment]
^ poslal som na to PR
