### ISSUE TITLE
Inconsistency between app detail (public vs. vendor)

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#117]
Ked pozeram detail aplikacie, tak response sa lisi. Konkretne field `vendor`.

Detail aplikacie cez public api call:

![screenshot_2017-06-30_10-41-45](https://user-images.githubusercontent.com/419849/27727935-c5060270-5d80-11e7-9c77-c69057510827.png)

Detail aplikacie skrz vendora:

![screenshot_2017-06-30_10-41-56](https://user-images.githubusercontent.com/419849/27727989-f31b2348-5d80-11e7-86d5-56147f023f90.png)

**Comment by ujovlado** [comment]
Tu je diff: 

```diff
--- aaas.json   2017-06-30 10:51:12.177887160 +0200
+++ bbbs.json   2017-06-30 10:51:27.013887172 +0200
@@ -6,8 +6,11 @@
   "configurationFormat": "json",
   "configurationSchema": {},
   "cpuShares": 1024,
+  "createdBy": "support@keboola.com",
+  "createdOn": "2017-01-09T09:42:38.000Z",
   "defaultBucket": true,
   "defaultBucketStage": "in",
+  "deletedOn": null,
   "documentationUrl": "https://help.keboola.com/extractors/database/mongodb/",
   "emptyConfiguration": {},
   "encryption": true,
@@ -31,6 +34,7 @@
   "longDescription": null,
   "name": "MongoDB",
   "network": "bridge",
+  "permissions": [],
   "processTimeout": 14400,
   "replacementApp": null,
   "repository": {
@@ -48,11 +52,6 @@
     "genericDockerUI"
   ],
   "uri": "docker/keboola.ex-mongodb",
-  "vendor": {
-    "address": "Křižíkova 488/115, Praha, CZ",
-    "email": "support@keboola.com",
-    "id": "keboola",
-    "name": "Keboola"
-  },
+  "vendor": "keboola",
   "version": 9
 }
```
... tie co su tam vo "vendor" api call naviac ma netrapia

**Comment by JakubMatejka** [comment]
Něčemu to vadí? Vendor ve výpisu svých aplikací nepotřebuje vidět svý kontaktní údaje, ne? Ten `vendor` field by tam nemusel být spíš vůbec

**Comment by ujovlado** [comment]
Nejedna sa o vypis aplikacii ale detail. Ide skor o to aby sa na to dali pouzit tie iste komponenty + aby sme nemuseli robit dalsi api call na detail vendora, ked si pozeras detail aplikacie.

Ked sa to prida tak vieme mat cely detail aplikacie pokryty jednou react komponentou a lisit sa budu len v tom, kde ake fieldy zobrazime.

**Comment by JakubMatejka** [comment]
Jasně, detail, to je jedno. Pořád mi není moc jasný proč bych potřeboval ve správě svých aplikací v detailu vidět svoje kontatktní údaje. Ale ok, tomu technickýmu argumentu rozumím. ;o)

**Comment by ujovlado** [comment]
List public apps, tam tiez dava len "vendorId":

![screenshot_2017-07-24_22-13-09](https://user-images.githubusercontent.com/419849/28542676-4bc156f8-70bd-11e7-8ae3-2ef73f65f2b6.png)

**Comment by JakubMatejka** [comment]
Vendora upravím na ten objekt, ale `createdOn`, `createdBy`, `deletedOn` a `permissions` obzvláště by v public detailu být neměly.

**Comment by ujovlado** [comment]
Ok, slo mi hlavne o ten vendor field .... tie co nam z bezp. dovodov nedavame, tie mi nevadia.
