### ISSUE TITLE
Add more (all?) fields to app list in admin API call

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#125]
List apiek ponuka opat male mnozstvo fieldov.
Api call: `/admin/apps`

Napr.

```
{
  "id": "tomaskacurtest.app-aaa",
  "version": 4,
  "name": "aaa",
  "type": "application",
  "createdOn": "2017-07-26T14:07:02.000Z",
  "createdBy": "**@keboola.com",
  "isPublic": false,
  "legacyUri": null
}
```

Nestalo by za to tam vracat vsetko, aby to bolo totozne s tym co vracia detail? Takto je to dost nekonzistentne.

Co sa kodu tyka, ja by som tam kludne robil `SELECT * ... `, a potom mal nejake metody "to API response" pre jednotlive casti.

Ale vzdy by som vracal to co je v detaile. T.j. ked zavolam list apiek (to je jedno v ktorej casti) a vrati mi ich to povedzme 20, malo by to byt to iste ako ked si zavolam 20 krat detail a poskladam si to.

Podobnu vec sme riesili tu: https://github.com/keboola/developer-portal/issues/116

**Comment by JakubMatejka** [comment]
To je prostě seznam s pár údaji pro výpis a detail potom obsahuje všechny
informace. Co je na tom nekonzistentní? Můžu to teda dát všechno do výpisu,
ale pak nevidím moc smysl v tom, aby tam byl zvláštní call pro detail.

2017-07-31 21:03 GMT+02:00 Vladimír Kriška <notifications@github.com>:

**Comment by ujovlado** [comment]
Jo, chapem, ze je to zoznam s par udajmi - nechapem ale preco tam nie je vsetko :). Nedava mi zmysel, aby tam tie udaje neboli vsetky (tak ako v detaile). Proste ked si volam list entit, chcem dost ich udaje kompletne, nie ciastocne.

Detail samozrejme zmysel dava, napr. mozes navstivit app na konkretnej URL (detail apky), a jediny API call, ktory budes potrebovat je prave ten detail (nebudes si kvoli tomu fetchovat vsetky). Dalsi use case je napr. ziskanie detailu app po jej editacii, ked si chcem refreshnut len jednu app (to sa ale da vyriesit tiez inak, v response - je uz na to issue).

**Comment by ujovlado** [comment]
Kukni sa napr. na Github ako to maju: https://developer.github.com/v3/issues/

**Comment by ujovlado** [comment]
Konkretny priklad.

Mam zoznam aplikacii: `GET https://apps.keboola.com/admin/apps`. Tento zoznam mi vracia minimalne info o aplikacii (chyba napr. `icon`, `vendor` a pod.)

Nasledne chcem jednu z tychto apps zmazat. Nie som ale schopny to urobit (prave kvoli chybajucim fieldom), pretoze nemozem poskladat API call `DELETE https://apps.keboola.com/vendors/{vendor}/apps/{app}`. Ak by som to chcel spravit, tak workaround bude, ze si najskor ziskam detail aplikacie, a az tak ju zmazem - co mi pride blbost.

**Comment by ujovlado** [comment]
@JakubMatejka tu este usla jedna vec ... pre list apiek v admin api call to vracia ikonky separatne (ako `icon32` a `icon64`), namiesto objektu `icon`
