### ISSUE TITLE
admin API: remove/disable user

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#126]
User has cognito property `isEnabled` that allows user to log in. This could be used as isDeleted flag. 
New api call `DELETE admin/users/userId` would then set `isEnabled` property to false.

**Comment by JakubMatejka** [comment]
Nebudeme uživatele rovnou mazat, nebo mám spíš teda dělat API cally na enable/disable? Bylo by to k něčemu? (cc @ujovlado)

**Comment by ujovlado** [comment]
Neviem ale ako to mas v DB ( lebo take `ON DELETE CASCADE` by odfajcilo aj vsetky appky, ak to tak je) ... a este rozmyslam tie fieldy `createdBy` a pod., ci su to len "texty" alebo foreign kluce.

Myslim ale, ze z hladiska Cognito by sme asi mohli, aspon tam nebude bordel ... tu db si asi budeme musiet osefovat aby so zmazanim usera nezmizli ine veci.

**Comment by JakubMatejka** [comment]
Uživatelé v db vůbec nejsou (aspoň zatím), tj. `createdBy` jsou jen stringy bez relací.

**Comment by ujovlado** [comment]
Tak potom som za, mazme ich, aspon tam nebude bordel

**Comment by JakubMatejka** [comment]
ok 👍 (a pokud v db někdy přibudou, tak se stejně budou mazat jen nějakým `isDeleted` flagem)

**Comment by JakubMatejka** [comment]
Fixed in v2.21.0
