### ISSUE TITLE
user assigned to empty-string vendor after creation

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#127]
After creating an account and made request to join a vendor, the user is assigned to an empty-string vendor:
![image](https://user-images.githubusercontent.com/1412120/28824483-75d2ca8e-76c2-11e7-9dff-cc4f71878c98.png)

**Comment by JakubMatejka** [comment]
Co je to za API call z toho screenshotu?

**Comment by kacurez** [comment]
GET  admin/users
http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/list-users

**Comment by JakubMatejka** [comment]
Tvl. jsem slepej, už to vidím, díky. ;o)

**Comment by kacurez** [comment]
jasne ;)
btw som zistil ze to maju len developeri bez vendorov, takze ked sa developer prida k nejakemu vendorovi tak ten prazdny string prestane vracat.
