### ISSUE TITLE
List of users not returning some user

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#128]
Ani jeden z tychto api callov mi navracia @kacurez ani mna:

- http://docs.kebooladeveloperportal.apiary.io/#reference/0/admin-api/list-users
- http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/list-users

Vyzera to akoby nevracalo prihlasenych userov alebo nieco take (ale nemusi to byt ono)

**Comment by kacurez** [comment]
mne to nevriacia ani Vlada, takze v tych zoznamoch ktore vracaju api cally^^ nevidim seba(tomas.kacur[at]keboola.com) ani jeho

**Comment by JakubMatejka** [comment]
Mno, v Cognito je stránkování (mám na to issue #32), ale nečekal jsem že na něj narazíme tak brzy. ;o) Zdá se, že limit je jen 60, což je taky ale maximum. ;o/ Pro admin list to až takový problém nebude, response bude v `Link` hlavičce vracet url na next page. (Cognito používá na stránkování pagination token, tak to bohužel bude jinak než zbytek API, který používá limit a offset. Ale vlastně bych to časem mohl sjednotit a dát next page s posunutým offsetem taky do tý hlavičky.) 

Blbý je to u výpisu uživatelů v rámci vendora. Pole `profile` do kterýho se seznam vendorů uživatele ukládá totiž není filtrovatelný, takže ho musí filtrovat portál až ho stáhne k sobě. A tím se rozbije stránkování v Cognito (resp. každá stránka bude vracet jiný počet userů a některý nemusí vracet žádný aniž by byly nutně poslední stránkou). Buď to můžu vyřešit tak, že si ty stránky bude portál stahovat tak dlouho dokud nebude mít šedesát a pak se to bude muset nějak namapovat na  stránkování na straně našeho API, nebo budu muset přesunout seznam vendorů do jinýho user atributu. (tj. buď do `given_name` nebo `family_name` ;o) Čímž by se museli upravit stávající uživatelé. No, v každým případě to nedořeším dneska.

**Comment by kacurez** [comment]
nebolo by lepsie to info o vendors co je teraz v `profile` presunut do dedikovanej mysql tabulky? neviem si predstavit aky to ma dopad na ostatne veci ale pride mi to ako najjedoduchsie riesenie. ci?

**Comment by JakubMatejka** [comment]
Nó, teď je seznam vendorů usera v samotným tokenu. Muselo by se do každýho callu přidat jejich dotahání z db, včetně připojení a odpojení db i tam kde to teď není potřeba. Tj. hromada refaktoringu. ;o) Ale nevím, možná.

**Comment by kacurez** [comment]
jasne, imho stejne si to vyzaduje vacsi zasah..a asi to je lepsie aj pre vacsi pocet userov ktory casom bude narastat :)

**Comment by ujovlado** [comment]
1. Tu by som sa asi priklonil k tomu aby devportal sluzil len ako proxy ... t.j. ked ti cognito vrati ten pagination token, poslal by si ho dalej (a to iste opacne, ked ho dostanes v req. tiez by si ho poslal dalej)

2. Mne sa celkom paci ze je to v tokene. nevedeli by sme na to zneuzit field `status` (nemyslim `cognito:user_status`), vyzera, ze je searchable. neviem ale, ako je to z jeho dlzkou. Potom tam vidim este obmedzenie na filter string na 256 - takze neviem v kolkych vendoroch bude moct user byt (ale keby sme si povedali, ze nemozes byt clenom viac ako 5, mozno by to stacilo) ... a bude sa to dat vobec poskladat?

**Comment by ujovlado** [comment]
^ upravil som ten comment, moja otazka bola, ci budeme vediet vobec poskladat ten Filter param. Resp. neviem ako by vyzeral, ked by v status (vendors) bolo: `keboola,ujovlado,kacurez` a ja by som chcel userov pre vendora `kacurez`

**Comment by ujovlado** [comment]
Aha, pole `status` uz mame zabrate ... ale odpoved na ten Filter ma aj tak zaujima :)

**Comment by JakubMatejka** [comment]
Kua, tak to nepůjde, to filtrování umí nejspíš jen exact match a prefix (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#listUsers-property). Asi to budu muset prostě všechno natahat najednou do paměti a pak filtrovat, nebo si držet kopii v db jak navrhoval Kacurez. To se mi ale taky moc nelíbí.

Jinak limit na user atribut je 2048 znaků (http://docs.aws.amazon.com/cognito/latest/developerguide/limits.html), takže by to mělo být snad ok

**Comment by kacurez** [comment]
omg tak to su riadne lamy v tom cogite ze nepodporuju lepsi filter(aspon nieco ako contains)

**Comment by JakubMatejka** [comment]
BTW. stránkování admin userů funguje přes ten `Link` header a `paginationToken` parametr:

![developer portal 2017-08-09 15-39-56](https://user-images.githubusercontent.com/215660/29124378-08dbeaac-7d19-11e7-816e-c74c7548fcd6.png)

**Comment by JakubMatejka** [comment]
Mno, takže listování všech userů adminem má hotový stránkování s next page v `Link` hlavičce (ostatní výpisy ho dostanou taky, viz. #134) a listování userů vendora je fixnutý, ale zatím bez stránkování (viz. #135). Deploy už běží.

**Comment by ujovlado** [comment]
Bude v tom asi este maly bug, mam vendora `ujovlado` a pod nim 4x service account a 1x standard account. API vracia len 3+1. Chyba account `ujovlado+travis_test_3`.

`GET /vendors/ujovlado/users`:
![screenshot_2017-08-12_20-51-39](https://user-images.githubusercontent.com/419849/29243467-0e7fbef0-7fa0-11e7-8d8a-6dc7eaf915f5.png)
