### ISSUE TITLE
Edit any vendor as admin

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#129]
chyba admin podpora na editaciu detailu akehokolvek vendora. Sice je api call na edit vendora http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendors/update-vendor ale musim byt jeho clenom.

**Comment by kacurez** [comment]
tak to vypada ze edit vendor nefunguje vobec ani pre vendora ktoreho som clenom, mne to teda failuje a vracia 403 forbidden `message: Authorization header requires 'Credential' parameter...`

**Comment by ujovlado** [comment]
ked pozeram do `serverless.yml`, tak vobec nevidim path `vendors/{vendor}`
https://github.com/keboola/developer-portal/blob/314af58/serverless.yml#L273

**Comment by JakubMatejka** [comment]
Fixed. Má to fungovat i pro adminy, aniž by museli patřit k vendorovi
