### ISSUE TITLE
Přesun komponent na ECR

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#133]
Zatím sem dávám ty co dnes failnuly:

- [x] keboola.wr-google-sheets
- [x]  keboola.r-transformation
- [x] keboola.python-transformation
- [x] keboola.ex-adwords-v201705
- [x] keboola.ex-google-drive
- [x] keboola.ex-google-analytics-v4
- [x] keboola.ex-facebook-ads
- [x] keboola.ex-facebook
- [x] ex-sklik-v2
- [ ] wr-tableau-server
- [x] keboola.ex-s3
- [x] keboola.ex-dynamodb
- [x] keboola.wr-db-snowflake

Další komponenty:
- [x] db-writer-pgsql
- [x] db-writer-mysql
- [x] gooddata-extractor
- [x] curated-data-extractor
- [x] keboola.wr-google-drive
- [x] elastic-writer

Procesory:
- [x] keboola.processor.move-files
- [x] keboola.processor.merge
- [x] processor-transpose

**Comment by Halama** [comment]
Budu sem psát na které komponentě zrovna dělám...

**Comment by JakubMatejka** [comment]
Jdu na adwords, sklik, tableau-server

**Comment by Halama** [comment]
Super diky. Tady je vidět jak se to aktuálně dělá nejlépe https://github.com/keboola/python-transformation/commit/e0b97feb69a750a79fedf1f935e563032c9d1b27
Mělo by výcházet z tohodle https://github.com/keboola/docker-demo-app/blob/master/deploy.sh

**Comment by Halama** [comment]
@odinuv jak si nasadil ty python transformace? Jenom ta uprava a commit nestaci ne,
Jeste se musi udelat update na ECR v dev portalu ne?
Tady vidím že se nastaví jenom tag https://github.com/keboola/python-transformation/blob/master/deploy.sh#L24

**Comment by odinuv** [comment]
no vsak repository nastavim jednou na zacatku

**Comment by Halama** [comment]
jo ale jak si to udelal aby to neukazovalo na neexistujici repository?

**Comment by odinuv** [comment]
deploynu to a pak to zmenim - deployue se to na quay i ecr

**Comment by Halama** [comment]
jo to je ten trik, toho že tam zůstal i quay jsem si nevšiml.
A když by se quay vyhodil a do toho update commandu by se dalo uri i type tak by to prošlo taky bez nutnosti to pak ještě updatovat ne? https://github.com/keboola/developer-portal-cli-v2/blob/master/src/Keboola/DeveloperPortal/Cli/Command/UpdateAppRepositoryCommand.php

**Comment by odinuv** [comment]
u tech transformaci deploy na quay stejne zustane, takze jsem to neresil. Jo dalo by se to tam dat, ale v principu mi prijde trosku divny v kazdym deploy nastavovat repository a jeho typ

**Comment by Halama** [comment]
ok, jdu to vyzkoušet na `keboola.ex-dynamodb`

**Comment by odinuv** [comment]
transformace jsou hotovy, tak si vemu jeste facebook a facebook-ads

**Comment by odinuv** [comment]
no stejne je asi lepsi tam ten deploy do quay nechat pokud nemame jistotu, ze se ten image nepouziva

**Comment by Halama** [comment]
dynamodb je hotový, tam jsem ten quay úplně vyhodil u ostatních ho teda nechám.
Co myslíš tím že nemáme jistotu že se ten image nepoužívá?

**Comment by Halama** [comment]
dál jdu na `keboola.wr-google-sheets`

**Comment by ujovlado** [comment]
tiez som ten quay vyhadzoval, ked som prehadzoval mongo a gmail ... v nasej infre sa predsa nemoze stat, ze sa to pouziva inde, nie?

**Comment by Halama** [comment]
hele me ten quay tam dava smysl jenom kdyby si ten image nekdo chtel pullnout a hrat si s nim lokalne, coz vlastne stejne moc asi smysl nedava kdyz si to muze buildnout

**Comment by ujovlado** [comment]
jo, to si buildnu ... a stejne si myslim, ze z tych repozitarov to nejako nepropagujeme, ze "aha, tu je image, sprav si pull a bav sa" ... ak by to bola issue, mozeme skor rozsirit jednotlive readmes o sekciu ako to buildnut

**Comment by odinuv** [comment]
myslel jsem to tak, ze kdyz uz ten image existuje a je public, tak s nim mohl kdokoliv cokoliv udelat (i kdyz na nejakym extractor image je to asi nepravdepoodbny), takze kdyz ho opustime, tak by se mel dat aspon deprecated nebo tak neco

**Comment by odinuv** [comment]
facebooky hotovy, tak ja vemu jeste `keboola.ex-google-drive`

**Comment by Halama** [comment]
`keboola.wr-google-sheets` hotový, vezmu dál `keboola.ex-google-analytics-v4` a `keboola.ex-s3`

**Comment by Halama** [comment]
u každé komponenty počkám na sync do KBC a zkouším jí. Takhle třeba se zatím dá ověřit že už to jede z nového image https://papertrailapp.com/groups/23635/events?q=147946154733.dkr.ecr.us-east-1.amazonaws.com%2Fdeveloper-portal-v2%2Fkeboola.wr-google-sheets

**Comment by odinuv** [comment]
je to zalogovany i u jobu https://papertrailapp.com/groups/23635/events?focus=831857104108265481&q=using+image&selected=831857104108265481

**Comment by odinuv** [comment]
gdrive hotovej, jdu vod toho

**Comment by Halama** [comment]
U té S3 nešlo o komponentu, ta už v ECR je ale o procesor:
```
Application error: Cannot pull image 'quay.io/keboola/processor-move-files:0.1.2': (1) Error while pulling image: G
```
To nechávám na později :)

**Comment by Halama** [comment]
jdu na `keboola.wr-db-snowflake`

**Comment by Halama** [comment]
`keboola.ex-google-analytics-v4` hotový

**Comment by Halama** [comment]
@odinuv Koukám že všechny processory jsou na quay. V ECR by si to ale s ním mělo poradit v pohodě ne?

**Comment by Halama** [comment]
`keboola.wr-db-snowflake` taky hotový

**Comment by JakubMatejka** [comment]
S `wr-tableau-server` bude trochu problém. V Travisu to ještě ani není (Quay má trigger na release v Githubu) a nemáme ani testovací prostředí. Na vývoj nám nějaká česká firma na chvíli půjčila testovací server, ale trvalýho nic nemáme. ;o/

**Comment by Halama** [comment]
tvl, koukám že ten description se nějak přepisuje :) jsem tam přidal další komponenty a zmizely...

**Comment by Halama** [comment]
`keboola.wr-db-pgsql` hotový

**Comment by odinuv** [comment]
procesory by mely jet z ECR bez problemu, je to komponenta jako kazda jina

**Comment by JakubMatejka** [comment]
(jinak je v dev portálu pořád necelých 40 keboolích appek na quay (po odečtení těch co mají v názvu "deprecated" nebo "test"))

**Comment by odinuv** [comment]
takovy ty co se pouzivaji malo podle me muzem nechat vyhnit

**Comment by Halama** [comment]
JJ ted mi to říká 32 a to ještě není aktualizované o poslední.
![image](https://user-images.githubusercontent.com/903531/29120579-3ac5d3d8-7d0b-11e7-93a1-24bcdba5eaa9.png)

dělám na tech co běželi dnes.

**Comment by Halama** [comment]
`db-writer-mysql` hotový

**Comment by Halama** [comment]
Takhle to teď vypadá na instanci, to už je docela dobrý imho:
```
[root@kbc-us-east-1-syrup-docker-i-0c4064cbf409863f4 ec2-user]# docker images
REPOSITORY                                                                                        TAG                 IMAGE ID            CREATED             SIZE
builder-598af9f3ce9de                                                                             latest              5df3a3019dbe        2 minutes ago       1.119 GB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-db-mysql              0.2.4               c4e42030355d        11 minutes ago      1.636 GB
builder-598af481da8ee                                                                             latest              fb81ea3c1f6e        26 minutes ago      411.6 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/ex-sklik-v2                      2.3.0               36f746ffa67c        About an hour ago   546.1 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-db-snowflake          1.2.4               5b58684504e2        2 hours ago         643.4 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-google-analytics-v4   2.0.2               ff482982fd07        2 hours ago         496 MB
builder-598acfc03aabf                                                                             latest              032d39f6fb04        3 hours ago         1.119 GB
builder-598aeb40a16f9                                                                             latest              032d39f6fb04        3 hours ago         1.119 GB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-google-drive          2.1.3               0c2faacb11e4        3 hours ago         662.6 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-google-sheets         1.0.9               46899c668e7a        3 hours ago         662.6 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-facebook              3.8.3               5e83dcd239f3        4 hours ago         860.3 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.r-transformation         1.1.1               729b730f3fe2        4 hours ago         1.836 GB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.python-transformation    1.1.1               0ea10f759a82        5 hours ago         1.122 GB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.custom-science-php       1.1.1               6b3839f8bbcf        22 hours ago        409.9 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/dca-custom-science-python        1.3.3               c104937ac933        23 hours ago        1.119 GB
dataweps/keboola_trendlucid                                                                       latest              6753d352ff54        36 hours ago        695.4 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-pgsql              1.3.8               ee81acb0f99d        5 days ago          753 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-redshift           1.0.4               41d654b64d19        6 days ago          1.026 GB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-mysql              1.0.12              a6dabde54145        6 days ago          396.9 MB
esnerd/keboola-bingads-ex                                                                         latest              9e07014de8d2        10 days ago         155.2 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-mongodb               v1.10.2             747391d41b88        13 days ago         590.2 MB
esnerd/keboola-ex-leonardo                                                                        latest              03e8de09e5ae        2 weeks ago         756.5 MB
mhumpolec/kbc-salesforce-extractor                                                                latest              885607825bc0        3 weeks ago         751.1 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/keboola/ex-generic-v2                                2.2.0               8124fdd20e0f        3 weeks ago         422.4 MB
quay.io/cleveranalytics/etl-t-area-mapper-geopandas                                               latest              dad2dafb3290        4 weeks ago         997.4 MB
alpine                                                                                            latest              7328f6f8b418        6 weeks ago         3.962 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.wr-redshift-v2           1.1.3               e1a97151888a        6 weeks ago         520.1 MB
quay.io/keboola/db-writer-pgsql                                                                   1.1.6               e0c650b981df        12 weeks ago        1.08 GB
quay.io/keboola/processor-transpose                                                               1.2.5               7992befc2920        3 months ago        404.5 MB
147946154733.dkr.ecr.us-east-1.amazonaws.com/keboola/ex-s3                                        1.1.0               927f783a2d1a        4 months ago        425.4 MB
quay.io/keboola/processor-merge                                                                   0.1.0               0a6a42cf5094        4 months ago        4.019 MB
quay.io/keboola/processor-move-files                                                              0.1.2               efbece6e11a4        4 months ago        4.019 MB
radektomasek/keboola-wr-sftp-webdav                                                               latest              597c6a872f53        4 months ago        677.7 MB
radektomasek/keboola-wr-s3                                                                        latest              99258ebb515a        6 months ago        696.9 MB
docker                                                                                            1.11                759b83b2afbb        7 months ago        75.76 MB
quay.io/keboola/elastic-writer                                                                    0.5.0               7c92cfb7e7ac        10 months ago       428.3 MB
quay.io/keboola/cadvisor-app                                                                      v0.10.0             ec0e22571b1a        13 months ago       1.3 GB
keboola/docker-ex-twitter                                                                         latest              cd96755856ba        14 months ago       663.5 MB

```

**Comment by Halama** [comment]
půjdu teď na ty procesory asi.

**Comment by Halama** [comment]
`keboola.processor.move-files` hotový

**Comment by Halama** [comment]
`keboola.processor.merge` hotový

**Comment by Halama** [comment]
^ ty by měly pokrývat S3 extraktor a používají se

**Comment by Halama** [comment]
`keboola.processor.transpose` hotový

**Comment by Halama** [comment]
`keboola.wr-google-drive` hotový

**Comment by Halama** [comment]
`keboola.ex-curated.data` a s ním `keboola.ex-currency` - používají stejný image

**Comment by Halama** [comment]
`keboola.ex-gooddata` a `keboola.wr-elasticsearch` taky hotový

**Comment by Halama** [comment]
ten `wr-tableau-server` zatím radši vynechám, není zdockerovaný ani se nebuilduje na travisu a nemáme ty credentials

**Comment by ujovlado** [comment]
bigquery extractor: https://github.com/keboola/google-bigquery-extractor/pull/32
