### ISSUE TITLE
can not remove service account

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#136]
pri pokuse o delete servise accountu(delete `/vendors/keboola/users/keboola+tomas_test2`) hodi chybu:
`422 Unprocessable Entity`
`Parameter email in uri must be valid email address`
tie service accounty nemaju email a tak to imho pada na validacii email parametru.
api call http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendor/remove-user-from-a-vendor

**Comment by JakubMatejka** [comment]
Jo no, jenže to jsou servisní účty k tomu vendorovi, tj. ani by se neměly moct z něj odebrat. Spíš by tam měla být možnost je smazat. Vlastně by to mohl umět ten samej API call. Běžnýho usera odebrat, servisního smazat.
