### ISSUE TITLE
list service accounts as standalone api call

### ISSUE THREAD

**Issue by kacurez** [keboola/developer-portal#137]
api call vracia vsetkych userov vendora vcetne servis accountov
http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendor/list-users

Na ui mame pre service accounty samostatnu stranku, na ktorej sa zobrazi zoznam userov ofiltrovany len na service accounty. Ak sa zavedie paginacia tak sa to bude zobrazovat divne pretoze napr jedna stranka bude obsahovat len jeden service account z page limit takze na stranke service accounts sa zobrazi jeden account + link na next page.

Preto by bolo lepsie zaviest novy api call ktory vrati len service accounty a v list-users ich nevracat.

**Comment by JakubMatejka** [comment]
Kua, to je naprd. Když dám flag jestli jde o běžnýho n. servisního uživatele do nějakýho filtrovatelnýho atributu, tak se nebude moct filtrovat už na nic jinýho, jde to jen na jednom atributu. Cognito má sice user groups do kterých by je šlo oddělit, jenže ty zase nejdou filtrovat vůbec. ;o) 

Čím dál víc přemýšlím nad ukládáním uživatelů do db, tím by se vyřešilo všechno, i to listování uživatelů podle vendora.

**Comment by JakubMatejka** [comment]
Viz. http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendor/list-users
V url je přepínač `service=`. Pozor na response, změnil jsem `email` na `username` a uživatelský účty mají `name`, kdežto servisní `description`
