### ISSUE TITLE
API calls ending with 4xx not returning "CORS" headers

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#140]
Ked dostanem 4xx error (v tomto pripade 401), vobec to nevrati Access-Control-Allow-Origin hlavicku

![screenshot_2017-08-14_14-04-13](https://user-images.githubusercontent.com/419849/29271286-f36dcb8c-80fa-11e7-9bdd-6cf181c6db09.png)

**Comment by JakubMatejka** [comment]
Aplikační 4xxky tu hlavičku vrací, tohle (expirovaný token) se odchytí v API Gateway a do aplikace se to vůbec nedostane. Podívám se, jestli se s tím dá něco dělat

**Comment by ujovlado** [comment]
Asi by malo: http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html :)

**Comment by JakubMatejka** [comment]
No, to co posíláš je dokumentace k nastavení CORS u API endpointů, kterou samozřejmě používáme. To o čem mluvím já, je vyfailovaný API call, který se nedostane k žádné resourse definované v API Gatewayi, tzn. ani k jejímu nastavení CORS.

**Comment by JakubMatejka** [comment]
(tzn. že vyfailuje ještě předtím, než má možnost zjistit, že ta resoursa, na kterou je url napojený, nějaký CORS nastavený má)

**Comment by JakubMatejka** [comment]
No, naklikal jsem to tam zatím ručně. Nicméně to nejde nastavit v CloudFormation, takže nevím jestli se to při příštím deployi nevrátí do původního stavu. ;o/
![api gateway 2017-08-15 15-44-35](https://user-images.githubusercontent.com/215660/29318556-d044a79e-81d0-11e7-96df-3a29919962ef.png)

**Comment by JakubMatejka** [comment]
To je vlastně duplikát https://github.com/keboola/developer-portal/issues/109. Jinak v CF už to jde nastavit, právě to řeším.
