### ISSUE TITLE
Service accounts not returning some users

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#144]
Mam service account `ujovlado+test_4`, no api mi ho nevracia.

![screenshot_2017-08-17_22-43-32](https://user-images.githubusercontent.com/419849/29432985-c80cbb88-839d-11e7-8fa1-7397ce2ed546.png)

Myslim, ze podobnu vec som uz raz reportoval, no to bolo tusim este pred prerabkou na ukladanie do db.

**Comment by JakubMatejka** [comment]
Hele ale ten byl smazanej
![devportalv2 dev-portal prod 2017-08-19 20-23-02](https://user-images.githubusercontent.com/215660/29489230-39057238-851c-11e7-98af-2c7f20de814b.png)

**Comment by ujovlado** [comment]
Aha, tak uz viem.

Takto:
- vytvoril som `test_10`
- zmazal som `test_10`
- potom som ho znovu vytvoril (a dostal som nove credentials)
- a nasledne ho API nevracia

T.j. vyzera, ze pri opatovnom vytvoreni mu neresetne flag `deletedOn`.

Neviem ale ci je to tak ma byt a ma povolit vytvorit takeho, co som uz raz zmazal. :)

**Comment by JakubMatejka** [comment]
No jo, kua. Ale v zásadě by to vadit nemuselo, ne? Když to nevadí Cognitu. ;o) Pokud se vytvoří znovu běžnej uživatel, tak je z povahy emailu víceméně jasný že to je ta samá osoba. U servisních účtů to tak sice není, ale pro zjednodušení bysme mohli říct, že jo. ;o) Myslím kvůli referencím. Zakázat vytvářet účet znovu by bylo zejména u těch servisních účtů asi dost otravný, za pár měsíců by to mohlo dopadnout tak, že to budeme pět minut zkoušet než trefíme název, který ještě nebyl použitý. Takže bych jen fixnul, aby se při vytvoření vynuloval `deletedOn` (a nejspíš by se teda měly smazat i reference na vendory). Co myslíš?

**Comment by ujovlado** [comment]
Myslim, ze nevadi, ze sa "reusuju" :) t.j. pokial sa to bude zvonku chovat spravne, je to imho fajn. A tiez to s tym vendorom - aby sme tam nevycarovali nejaku "dieru".

Spominam si ale, ze sme sa v niektorom issue bavili, ze by sa useri mazali uplne. A ak ich mazes v Cognito, kludne by som ich mazal aj u nas - je to taka istota a nemusis potom riesit veci okolo "deletedOn" a pod.

**Comment by JakubMatejka** [comment]
Vlastně máš pravdu, nedošlo mi, že z aplikací na usery nevedou reference, takže je klidně můžu mazat. To bude určitě lepší

**Comment by JakubMatejka** [comment]
Jo, ještě mi prosím řekni, který mám smazat a který nechat:
![devportalv2 dev-portal prod 2017-08-21 17-59-31](https://user-images.githubusercontent.com/215660/29527928-886e7ac0-869a-11e7-8655-b8f760b3979d.png)

**Comment by ujovlado** [comment]
@JakubMatejka podla tohto screenshotu kludne zmaz vsetky, co maju `deletedOn` ;)

**Comment by JakubMatejka** [comment]
Tak ty `ujovlado+test_*` jsem nechal, protože jsou v Cognito, tak aby to nedělalo bordel. ;o)
