### ISSUE TITLE
Add app approval requests to db

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#145]
To be able to list them in the ui

**Comment by JakubMatejka** [comment]
Dělám na výpisu žádostí o schválení a chci se zeptat, jestli by byl pro vás ok formát:
```
[
  {
    "app": {
      "id": "appId",
      // atd. - stejný objekt jako ve všech výpisech včetně 'vendor' a 'icon'
    },
    "createdBy": "test@keboola.com",
    "createdOn": "2017-08-29 12:14:56"
  }
]
```
cc @kacurez @ujovlado

**Comment by ujovlado** [comment]
@JakubMatejka a nestacilo by pridat novu property do objektu apky? Napr. nejaky "status"?

Prepokladam, ze to momentalne zamyslas ako novy endpoint. No asi by sa mi pacilo, keby som zavolal `/admin/apps` a tam videl (podla spominaneho statusu), ci je apka na schvalenie.

Myslim, ze podobne to bolo navrhovane aj v designe:

![screenshot_2017-08-29_15-17-32](https://user-images.githubusercontent.com/419849/29822896-4b1f78ac-8ccd-11e7-8ffe-4e8e5d813c66.png)

**Comment by JakubMatejka** [comment]
No, appka jednak žádnou property status nemá, to by se muselo nějak poskládat z flagů `isPublished` a případných dalších. A potom asi chceme vědět kdo a kdy o to zažádal a z toho bych app property asi nedělal.(?)

**Comment by ujovlado** [comment]
Jasne, taka property tam nie je, preto pisem, ci by sme nieco take nepridali. :) Skor sa na to pozeram tak, ze chcem poskladat view ako je vyssie (v tom screenshote).

Cize napr. by sme mohli pridat do appky `approvalRequest`:

```json
{
  "id": "blabla",
  ...
  "approvalRequest": {
    "requestedBy": "test@keboola.com",
    "requestedOn": "2017-08-29 12:14:56",
    ...
  }
}
```
... mozno by sa tam hodili aj dalsie fieldy, neviem, co vsetko vieme/chceme userovi povedat, ked sa schvaluje apka (mozno este nieco ako `rejectedOn`?).

Co sa procesu tyka, viem si to predstavit takto:

1. schvalovanie:

- user poziada, cize v `approvalRequest` by bolo naplnene `requestedBy` a `requestedOn`:

```json
{
    "requestedBy": "test@keboola.com",
    "requestedOn": "2017-08-29 12:14:56",
    "rejectionReason": null,
    "rejectedOn": null
  }
```

2. zamietnutie

- v apkach user uvidi svoju app a bude tam mat navyse `rejectionReason`:

```json
{
    "requestedBy": "test@keboola.com",
    "requestedOn": "2017-08-29 12:14:56",
    "rejectionReason": "Missing default configuration",
    "rejectedOn": "2017-08-30 12:14:56"
  }
```

3. opatovne poziadanie:

- to co v korku 1, t.j. premaze sa `rejectionReason` a `rejectedOn` a fieldy `requestedBy` a `requestedOn` by sa nastavili na nove hodnoty.

```json
{
    "requestedBy": "vlado@keboola.com",
    "requestedOn": "2017-08-31 12:14:56",
    "rejectionReason": null,
    "rejectedOn": null
  }
```

... atd.

**Comment by ujovlado** [comment]
^ tak ako som to popisal, tak by este musel pribudnut novy endpoint na zamietnutie apky.

**Comment by JakubMatejka** [comment]
Ok. Datum odmítnutí asi není potřeba, bude to teda 
```
"publishingRequest": {
  "createdBy": "",
  "createdOn": "",
  "rejectionReason": ""
}
```
Jak by to mělo vypdat u appky, která tu žádost nemá, stačí `"publishingRequest": null`? (A implikuje to teda, že uživatel může tu žádost odeslat opakovaně několikrát za sebou.)

**Comment by ujovlado** [comment]
Ano, kludne moze byt `publishingRequest` nastaveny na `null`, ked je apka schvalena alebo este nebola odoslana na schvalenie.

To niekolkonasobne odoslanie na UI urcite neumoznime - nechces to zakazat aj na API?

**Comment by JakubMatejka** [comment]
No a jak bych to měl poznat? Z toho co jsi popsal vyplývá, že prázdný `createdBy` a `createdOn` bude jen při první žádosti o schválení. Když ji zamítneme, on zařídí opravu a pošle žádost znovu, tak už budou vyplněný (tj. podle nějakýho `createdOn IS NULL` to testovat nemůžu).

**Comment by ujovlado** [comment]
Aha, tak to, co som popisoval, bol len navrh. :)

Takze pri zamietnuti by to malo vyresetovat `requestedBy` a `requestedOn`, pretoze apka sa dostava vlastne do stavu ako bola pred odoslanim na schvalenie.

T.j. po zamienuti to bude vyzerat takto:

```json
{
    "createdBy": null,
    "createdOn": null,
    "rejectionReason": "Missing default configuration, please fix and send again"
  }
```

Na strane UI by som to osetril tak, ze dovolim odoslat na schvalenie iba ked je `createdOn` a `createdBy` nastavene na `null`.

**Comment by JakubMatejka** [comment]
Však jo a já se jen doptávám jak bys v rámci něj řešil tuhle věc. Nulování `createdBy` a `createdOn` mě taky napadlo, ale nechtěl jsem to úplně vnucovat, kdybys to měl vymyšlený jinak. ;o)) Ok, já myslím, že takhle to vypadá v pohodě.

**Comment by ujovlado** [comment]
Super

**Comment by JakubMatejka** [comment]
Na ten status jsem udělal samostatný issue: https://github.com/keboola/developer-portal/issues/147
