### ISSUE TITLE
Add app property publishingStatus

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#147]
Sestaví se dynamicky podle nastavení ostatních properties:
- `private` (~ `isPublic===0 && !publishRequestOn`)
- `requested` (~ `publishRequestOn`)
- `rejected` (~ `publishRequestRejectionReason`)
- `public` (~ `isPublic===1`)

**Comment by JakubMatejka** [comment]
Akorát se to trochu zkomplikuje, až se začne podporovat publikace do konkrétních kbc stacků

**Comment by ujovlado** [comment]
Rozmyslam este, ci je (momentalne) ten `status` potrebny - vlastne tak ako si to tu popisal to vieme poskladat aj na UI. :)

**Comment by JakubMatejka** [comment]
V kódu už to mám, stačí commitnout a pushnout, tak si řekni. ;o)

**Comment by ujovlado** [comment]
Tak ak zacneme podporovat publikovanie do viacerych stackov, tak sucastou `publishRequest` mozu byt aj regiony a ked sa to schvali apka bude dostupna v konkretnych regionoch (presunie sa to po schvaleni do `permissions.stack`?). Ale mozno to pojde aj lepsie.

**Comment by ujovlado** [comment]
A vies co, daj to tam (ten status), niekde to stejne musi byt. :)
