### ISSUE TITLE
Return whole app object also after publication request, approval and rejection

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#148]
Tak ako pri ostatnych metodach, co menia apku, bolo by fajn aj tu vracat cely objekt apky.

Opat to pomoze pri zobrazovani a nemusime riesit dalsie req. na ziskanie aktualneho stavu.

**Comment by JakubMatejka** [comment]
Je to tam, ale s výhradou. ;o) IMHO z hlediska API pro to není žádný relevantní důvod a už od školy slýchám, že když se API podřizuje ui, tak je v něm asi něco špatně. Ale asi už stárnu a časy se mění, nebo co. ;oD

**Comment by ujovlado** [comment]
:) Heh, no ja som zase cital, ze by si nemal robit API, pokial nepoznas jeho konzumentov.

Ale s5 k tomu dovodu.

1. ten co som popisal vyssie, ze po uspesnom update rovno dostatnem updanutu entitu, a tak vie UI poriesit update hned
2. usetri ti to load, pretoze inac by som po kazdej zmene musel robit reload, co by znamenalo 2x viac requestov, pretoze po kazdom update by nasledoval "reload"

**Comment by ujovlado** [comment]
Vzdy ked som si nie isty, zalovim pre inspiraciu tu: http://jsonapi.org/format/#crud-updating-responses. Zrovna pre update to tam popisuju celkom pekne a hovoria, ze "No content" mozes vratit ak sa po danom requeste resource nezmenil.

Samozrejme drzat sa toho nemusime :) Ale stavim sa, ze nech robis nad nasim API akukolvek apku, tak by si tie responses vyuzil a bol by si rad, ze ti to vracia cely resource apky ;)

**Comment by JakubMatejka** [comment]
V pohodě, to mi nemusíš vysvětlovat, já to v zásadě chápu. Jen jsem si nedopustil takový malý bezvýznamný povzdechnutíčko. 😛

**Comment by ujovlado** [comment]
@JakubMatejka akurat som sa s tym bavil a pozeram, ze to nevracia pre publishing request.

`POST /vendors/keboola-test/apps/keboola-test.app-vlado-test-9/publish` stale vracia "204 No Content"

Pridal by si to prosim aj tam?

**Comment by JakubMatejka** [comment]
Jasně, už je to v produkci

**Comment by ujovlado** [comment]
Super, diky, fici to
