### ISSUE TITLE
Create account app error (whitespace in password?)

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#149]
Vyzera, ze ked vytvaram account a v hesle mam medzeru, hodi to app error.

Priklad hesla: `ntain at least 8 chA`

```
{"errorMessage":"Application error","errorType":"ApplicationError","requestId":"0cf170bb-8f4e-11e7-9aa5-75cd007769f2"}
```

**Comment by JakubMatejka** [comment]
Fixed in https://github.com/keboola/developer-portal/releases/tag/2.29.2
