### ISSUE TITLE
Confusing message when resetting password / Don't reveal user existence

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#150]
Ked sa snazim resetnut si heslo a zadam neexistujuci email, dostanem error `Incorrect username or password.`

Jedna sa o `UserNotFoundException`.

Rozmyslam teraz, ako by sme to mohli fixnut:

1. bud upravime tu error hlasku na nieco "User with specified email doesn't exist"
2. alebo by to vobec nevracalo `403 Forbidden` ale vzdy `200 Ok` a hlaska by bola nieco ako "If user with specified email exists in our database, we'll send recovery link to it" (toto sme nedavno riesili, no uz si uplne nemapatam kde)

Ta 2. teoreticky nema vyznam, lebo "user existence" sa da vlastne overit pri registracii. Ale mozno je lepsie to mat len na 1 mieste, nie na 2. :)

**Comment by JakubMatejka** [comment]
Co že je s tím za problém? ;o) Ta hláška i status kód je z Cognito, portál ji jen převezme a pošle dál.

**Comment by JakubMatejka** [comment]
Jo už asi rozumím, tam se vlastně password nezadává. Ok, opravím spíš na 1.

**Comment by JakubMatejka** [comment]
Fixed in https://github.com/keboola/developer-portal/releases/tag/2.29.3

**Comment by ujovlado** [comment]
Diky, `User not found` je lepsie :+1:
