### ISSUE TITLE
Move assets under assets-cdn.keboola.com

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#151]
Rad by som nejako naplanoval presunutie assets pod novu Cloudfront distrubuciu, ktoru chystame (presunute uz je na nej `indigo-ui` a `kbc-ui`).

Ak spravne kukam, tak devportal ma s3 bucket, kde uploaduje ikonky a to je myslim vsetko.

Aby sme to mohli dat pod spominanu `assets-cdn`, potreboval by som upravit cestu, ako su tie ikonky ulozene v s3 buckete.

Momentalne:
- "dev portal bucket" -> `icons` -> `appId` -> ....

Po novom by som chcel:
- "dev portal bucket" -> `developer-portal` -> `icons` -> `appId` -> ...

Migraciu si viem predstavit nejako takto:

1. prichystame kod, ktory bude ikonky ukladat a servovat z novej cesty
2. skopirujeme `icons` do priecinka `developer-portal` (aby sme dosiahli cestu, ako som pisal vyssie)
3. hned potom by sa mal spravit deploy kodu z kroku 1.
4. (optional) mozeme zopakovat este raz bod 2. (ak sa medizcasom nahodou nieco zmenilo)
5. setupnem tento s3 bucket ako dalsi "origin" do cloudfrontu
6. overim, ze vsetko ide ako ma (ikonky z `assets-cdn.keboola.com/developer-portal/icons/....`
7. prichystame zmenu, ktora namiesto `d1ycqiwapkz1gh.cloudfront.net` pouzije `assets-cdn.keboola.com`
8. deploy kodu z kroku 7.

Kazdopadne, chcem to prekonzultovat, ci som na nieco nezabudol. Resp. kludne to mozeme spravit aj cez novy bucket (ale to mi pride komplikovanejsie).

**Comment by JakubMatejka** [comment]
@ujovlado Jasně, je to přesunutý ve stávajícím bucketu pod ten `developer-portal`. Takže teď asi setupni ten CloudFront a já potom změním base uri pro ty ikonky

**Comment by JakubMatejka** [comment]
(je to bucket `developer-portal-v2-resources`)

**Comment by ujovlado** [comment]
Jo, ja som to setupol uz doobedu, ked som videl ze na tom makas :)

Kludne to prehod, prave som skusil na ikonke `url.replace('d1ycqiwapkz1gh.cloudfront.net', 'assets-cdn.keboola.com')` a vsetky sa mi v UI zobrazili.

**Comment by ujovlado** [comment]
Este jedna vec, len pre istotu, hore som to nezmienil. Ten povodny priecinok `icons` v s3 este nejaku dobu nechajme, nez si to klienti poloaduju znovych URLs.

**Comment by JakubMatejka** [comment]
Tak je to překlopený. :+1:
