### ISSUE TITLE
Move from `apps.keboola.com` to `apps-api.keboola.com`

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#152]
Bavili sme sa, ze `apps.keboola.com`, kde je public vypis apiek je vlastne nahradeny UIckom a tym padom by sme mohli UI presunut na domenu, kde bolo doteraz API a api dat niekde inde.

Takze asi:
- prehodit `apps.keboola.com` na `apps-api.keboola.com`
- zrusit vypis apiek

Technicky to bude asi musiet chvilku ficat na dvoch domenach, potom prehodime vsetko pouzitie na novu domenu a az tak staru pouzijeme na nieco ine.
Vyskyty: https://github.com/search?utf8=%E2%9C%93&q=org%3Akeboola+%22apps.keboola.com%22&type=Code

Az to bude, tak ja potom prehodim `portal.keboola.com` na `apps.keboola.com`.

Resp. ak je to takto zle a su lepsie napady, sem s nimi.

Uprava pouzitia:

- [x] dev portal UI: https://github.com/keboola/developer-portal-ui/pull/304
- [x] connection: keboola/connection#996
- [x] developer docs: https://github.com/keboola/developers-docs/commit/95bc8fcf794037bf9fc82cb19406e9b49d787c00
- [x] devportal php client: https://github.com/keboola/developer-portal-php-client/pull/2
- [x] devportal CLI: https://github.com/keboola/developer-portal-cli-v2/pull/6

**Comment by JakubMatejka** [comment]
Jdu na to. Nastavení v API Gateway se dělá manuálně (https://console.aws.amazon.com/apigateway/home?region=us-east-1#/custom-domain-names) a zdá se, že půjde nejdřív nastavit obě varianty a potom teprve odstranit původní. Takže jdu přidat tu novou, potom deploynu dev portál s novou url (kvůli linkům na ikonky a linky z mailů) a potom můžeme pořešit ostatní appky.

**Comment by JakubMatejka** [comment]
Je to tam: https://apps-api.keboola.com, jdu zrušit ten html výpis appek

**Comment by ujovlado** [comment]
Super, inac s tymi updatmi komponent, co to pouzivaju mozem pomoct. Kludne si ich nejako rozhodme.

**Comment by JakubMatejka** [comment]
Tady je link na issue v connection: https://github.com/keboola/connection/issues/996

Co se týče portal klienta, tak pro deploy to mají asi všechny appky v Travisu v env proměnných, co? Ale asi bych pak původní url zrušil a zmigrují se postupně jak budou failovat deploye ;o)

A opravil jsem https://github.com/keboola/developers-docs

**Comment by ujovlado** [comment]
tu default URL tam idem pridat

**Comment by ujovlado** [comment]
Ok, ak spravne kukam, je to poriesene, chyba uz len uprava configov v connection.

**Comment by Halama** [comment]
jo na kbc to udelam asi zitra

**Comment by Halama** [comment]
kbc je hotove https://github.com/keboola/connection/issues/996#issuecomment-330772290

**Comment by ujovlado** [comment]
@JakubMatejka vyzera, ze je to teda ready :) Nechcem sa ti do toho montovat, uvolnil by si teda domenu "apps.keboola.com" (z Route 53 a pod.), aby som na nu presunul devportal?

**Comment by ErikZigo** [comment]
```
Martin Lepka
31 minutes ago
 
ahaaa, btw vypada super ten dev portal :) skoda ze nefunguje apps.keboola.com protoze to mame ve velke spouste biz komunikaci...
```

**Comment by ujovlado** [comment]
@ErikZigo apps.keboola.com coskoro bude ficat (bude tam devportal ui).

**Comment by ErikZigo** [comment]
Ja nevim co je coskoro, vcera martin rekl za chvili :-)
Tady to vypada ze cekas jen na to DNS?

Martin Lepka vcera rikal ze mu nejde vypis komponent apps.keboola.com. Tak jsem mu dal info ze jsou treba na developer portalu a ze se ho tam chystame presunout.

Dneska  prave psal to ^^^ ze ten apps.keboola.com pouzivaji v komunikaci. Tak kdyz nekolik dni apps.keboola.com tak je to asi skoda.

**Comment by Halama** [comment]
tou chvili jsem myslel par dni. apps.keboola.com nikdy neslo oficalne ven co vim.

**Comment by ErikZigo** [comment]
Ja popravde ani nevim co tam predtim bylo :D

**Comment by JakubMatejka** [comment]
Hotovo
