### ISSUE TITLE
MFA Authorization Docs

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#155]
https://github.com/keboola/developer-portal/blob/c469cb17c259af18b61a9e809aadbdf9a34def0d/apiary.apib#L76 says i should send a password with the session and code, but the password MUST NOT be there.

**Comment by JakubMatejka** [comment]
A jak by to teda mělo vypadat, když první call password vyžaduje a druhý ne?

![developer-portal 2017-09-21 10-06-14](https://user-images.githubusercontent.com/215660/30685249-9855cbbe-9eb4-11e7-8800-48dc6e1be132.png)

**Comment by JakubMatejka** [comment]
A jak by to teda mělo vypadat, když první call password vyžaduje a druhý ne?

![developer-portal 2017-09-21 10-07-45](https://user-images.githubusercontent.com/215660/30685309-c6c72290-9eb4-11e7-85b9-2ad3748f7f4e.png)

**Comment by ondrejhlavacek** [comment]
Zmátl mě ten úvodní text

> If your account has activated MFA, login with `email` and `password` returns `session` which is used in subsequent login call along with the code recieved in text message.

Přišlo mi, že mám k tomu requestu přidat `code` a `session` a poslat to znovu :-)

Kdyby tam bylo třeba něco jako...?

```
+ Attributes
    + email (required)
    + password (use only in the first step of MFA)
    + session (use only in the second step of MFA)
    + code (use only in the second step of MFA)
```
Btw proč to je ten samej endpoint? Je to nějaká běžná praktika, nebo třeba kvůli Cognitu?

**Comment by JakubMatejka** [comment]
Ok, fixnu to. Nó, je to stejnej endpoint protože šetřím s CloudFormation resoursama. Už se zase nebezpečně blížím limitu. 😃 Jinak žádný extra důvod.

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/developer-portal/commit/63874a5ebceec0c32062447cec28517982d34fd5
