### ISSUE TITLE
Tune email when user joining existing vendor.

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#156]
![2017-09-21](https://user-images.githubusercontent.com/419849/30703824-10cf30da-9ef1-11e7-963a-cbd6e73ad456.png)

**Comment by ujovlado** [comment]
Mozno zatial kym to nemame v UI, tak nieco taketo:

User **Hanka** (hanka@hanka.com) wants to become a member of your vendor **Genea**. You can approve this request by calling Developer Portal API http://docs.kebooladeveloperportal.apiary.io/#reference/0/vendor/accept-request-to-join-a-vendor

**Comment by ujovlado** [comment]
cc @hhanova

**Comment by hhanova** [comment]
jo, to je pekny. Tomu by prej rozumeli. Jen doted nevedeli, ze jsou nejakej vendor a ze jsou pod tim vendorem lidi.

**Comment by ujovlado** [comment]
@hhanova to je dobry point a pri spustani developer portalu pre vsetkych by sme mohli poslat mail existujucim vendorom s informaciami o tom, ze su u nas evidovani ako vendor a co to obnasa.

**Comment by JakubMatejka** [comment]
Fixed in https://github.com/keboola/developer-portal/releases/tag/2.29.1
