### ISSUE TITLE
Require at least 128x128px icon

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#158]
Bolo by fajn, ak by sme pre nove apky pozadovali ikonku 128x128px.

Vyriesime tym 2 veci:

- neostrost na HDPI/retina displejoch
- zobrazenie ikony podla navrhu, ktory dodal Jack.

Potom by mohlo pribudbut v response aj `128`, ak taku velkost apka ma.

**Comment by JakubMatejka** [comment]
Hm, to je trochu problém, protože lambda funkce zpracovávající uploadnutý soubor se triggeruje asynchronně po nahrání souboru do s3. Tzn. při pokusu o upload souboru s menšími rozměry (což je PUT na pre-signed url v s3) nejde vrátit chybu. Přemýšlím jak by se to tak dalo řešit..

**Comment by ujovlado** [comment]
Aha, no je to kozmeticka vec a mozeme to poriesit zatial tak, ze tam pridame validaciu na frontende. Ak tam niekto uploadne cez api nieco mensie, 128x128 bude neostre a uploadne tam novu, lebo sa mu to nebude zdat ok.

**Comment by ujovlado** [comment]
Takze az to budem mat pripravene (ze cez ui sa nebude dat uploadnut mensia ako 128x128), tak mozeme pridat ten novy rozmer, ako pisem vyssie.

**Comment by JakubMatejka** [comment]
Ahá, takže tam mám přidat další rozměr 128x128, to jsem prve úplně nepochopil. Dodělám

**Comment by JakubMatejka** [comment]
Hotovo
