### ISSUE TITLE
Vendor Project

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#159]
Support při schvalování vendora založí projekt a bude potřeba ho k vendorovi uložit. Asi stačí jen Connection URL (pro různý regiony) a Id projektu, nebo možná rovnou celá cesta k projektu? Bude se hodit v UI na přímej link na appku do projektu.

**Comment by ujovlado** [comment]
Pre koho ma byt ten "přímej link na appku do projektu"? Pre normalneho user devportalu? Alebo si myslel len testovaci projekt vendora?

**Comment by ondrejhlavacek** [comment]
Kdo je normální user? Myslel jsem ten testovací projekt vendora.

**Comment by JakubMatejka** [comment]
Asi vůbec nevím o co jde. Ale u appky prostě jen přibude nový atribut? Třeba `testProjectUrl`?

**Comment by ujovlado** [comment]
Chapem to tak, ze chceme pridat novy parameter k vendorovi, kde ulozime (pri schvalovani vendora) URL (alebo id+region) na testovaci projekt. Neviem ale ako to budeme riesit dalej, ci to produkcne projekty alebo ake a kto to bude v pripadne exspiracie obnovovat pripadne menit "test project url" a pod. Zda sa mi to dost nesystemove.

**Comment by ondrejhlavacek** [comment]
A jak bys to řešil systémově? Definice projektu je popsaná tady - https://developers.keboola.com/#development-project. Expiraci nastavenou nemaj a url by se měnit třeba pro vendora nemuselo?

**Comment by ujovlado** [comment]
To zatial neviem - nejako automaticky. Napr. pri prekliku do connection si vyberes region -> potom si redirectnuty na specialnu URL (uz v connection konkretneho regionu), kde si vyberes z projektov, ktore mas dostupne -> nasledne si redirectnuty na stranku apky. (co by sa mozno dalo pouzit aj na vseobecne prepojenie, kedy si kazdy moze pridat apku do svojho projektu)

A budeme to kontrolovat, ze dodrzuju tie podmienky? Skor mi ale slo o to, aby sme neprodukovali odkazy do neexistujucich projektov.

**Comment by ondrejhlavacek** [comment]
No vždyť ten projekt tomu vendorovi zakládáme, tak jde jenom o jeho evidenci a usnadnění prokliknutí se na appky, který nejsou public. Projektů může mít víc, ale jen jeden bude jeho "vendor/developer testovací projekt". Žádný neexistující linky tam nebudou.

**Comment by ujovlado** [comment]
Ano, ved to chapem. Len sa mi to nepozdava a spravil by som to radsej nejako lepsie aby link do projektu v connection nezalezal od toho, co tam vlozime.

**Comment by ondrejhlavacek** [comment]
No, přijde mi to pro tenhle use case zbytečně komplikovaný. Tlačítko typu `Show in sandbox project` za sebou víc logiky mít nemusí :-)

**Comment by ujovlado** [comment]
Asi nech prida nazor este niekto iny :wink: mne sa ten napad, s ukladanim URL na project do atributov vendora nepaci.

**Comment by odinuv** [comment]
@ujovlado je to proste *testovaci projekt vendora*, zalozime vendora a soucasne mu udelame testovaci projekt (zatim rucne, casem treba automaticky, to je fuk) jeden vendor ma jeden testovaci projekt - to mu musi stacit. Takze by se melo ulozit sapi_url a project_id 
nijak bych to nekomplikoval a prijde mi to uplne systemovy

**Comment by ujovlado** [comment]
@odinuv prislo mi to divne, ze nejaky redirect na project sa odvoja od toho, co niekto pastne do nastaveni vendora (vznika tam priestor na chyby). Dalsia vec, kto to bude udrzovat aktualne? Vyexspiruje projekt a nam vznikne nefunknca URL.

Preto som to chcel spravit ako popisujem tu: https://github.com/keboola/developer-portal-ui/issues/357 - bolo by to univerzalne a mohol by si si pozriet ktorukolvek apku v ktoromkolvek tvojom projekte. A vyzadovalo by to len malu upravu v connection na domovskej stranke, kde vyberas projekt.

Ale asi ak to bude komplet automatizovane, som za.

**Comment by odinuv** [comment]
podle me neni moc zadouci, aby sis "mohol by si si pozriet ktorukolvek apku v ktoromkolvek tvojom projekte" (ne, ze bych tomu chtel branit), ale meli bysme imho tlacit vendory do toho at si testuji veci v testovacim projektu a ne na zakaznikovi. Dev projekt nema co expirovat, takze me to neprijde jako problem

**Comment by ondrejhlavacek** [comment]
Jj, jinak se o týhle featuře budem moct bavit další rok :-)

**Comment by ujovlado** [comment]
Ved kludne, nech sa to tam storuje. Ja som to bral ako feature pre usera devportalu - to tlacitko “Add to Keboola Connection” a storovat to, mi prislo ako duplicita.

Ale vlastne tie veci mozu existovat nezavisle, mozeme mat button na pridanie do connection “Add to KBC” a dalsi button pre developerov “Add to test project” -> ale to uz je na UI.

**Comment by JakubMatejka** [comment]
Je ok, když ta `projectUrl` property bude editovatelná i vývojářema vendora (tj. i v tomhle callu https://kebooladeveloperportal.docs.apiary.io/#reference/0/vendor/update-a-vendor), nebo na to mám udělat API call jen pro adminy? (Raději bych šetřil resoursama v CF templatě, pokud to jde. ;o)

**Comment by odinuv** [comment]
podle me je mit to editovatelny vyvojarema

**Comment by JakubMatejka** [comment]
Fixed in https://github.com/keboola/developer-portal/releases/tag/2.36.0
