### ISSUE TITLE
Wrong name in message to slack when creating new vendor

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#161]
Looks like vendor name is also used as name in email.

Example:
`User Keboola Czech <martin.matejka@keboola.com> requires creation of vendor Keboola Czech`

Should be:
`User Martin Matejka <martin.matejka@keboola.com> requires creation of vendor Keboola Czech`

Here, it looks fine, so I don't know where can be a problem:
https://github.com/keboola/developer-portal/blob/510641c6e30eb95bc6c0fc04726ce9c4c2f29646/lib/notification.js#L15

**Comment by JakubMatejka** [comment]
Fixed
