### ISSUE TITLE
Ability do delete vendor

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#162]
It could be useful to have an api call to delete vendor. Vendor deletion should be allowed only if there are no apps associated with it (e.g. moved to another vendor).

**Comment by ujovlado** [comment]
^ of course, only as admin and only if there are no apps.

**Comment by JakubMatejka** [comment]
No, tak je to tam: https://kebooladeveloperportal.docs.apiary.io/#reference/0/admin-vendors/delete-a-vendor Trochu blbý je, že informace o příslušnosti ke smazanýmu vendorovi zůstane uživateli v Cognito profilu a tenhle call ji pořád vrací: https://kebooladeveloperportal.docs.apiary.io/#reference/0/auth/get-user-profile Můžu ho upravit, aby vracel jen ty nesmazaný, ale v Cognito, tzn. i v JWT tokenu ta informace zůstane. A vy si ji načítáte v ui, že?

**Comment by JakubMatejka** [comment]
Jinak samozřejmě nad smazaným vendorem nic dělat nejde.

**Comment by JakubMatejka** [comment]
Smazaný vendor dostane v db flag `deletedOn`, fyzicky se nemaže (takže mj. nepůjde vytvořit nový se stejným jménem)

**Comment by ujovlado** [comment]
> v Cognito, tzn. i v JWT tokenu ta informace zůstane

@JakubMatejka aj po odhlaseni a naslednom prihlaseni?

**Comment by JakubMatejka** [comment]
jj. Ale vlastně bych mohl z rdska zjistit seznam uživatelů vendora a pak jednomu po druhým upravit ten záznam o příslušnosti k vendorům v Cognito.

**Comment by JakubMatejka** [comment]
Tak hotovo
