### ISSUE TITLE
ECR apps

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#163]
Když nastavím v UI, že chci appku v ECR, tak neumím nastavit ani jeden z parametrů.

![image](https://user-images.githubusercontent.com/497675/32499457-edb9146a-c3d2-11e7-82c8-baacd76537b8.png)

Když nastavím automatickej deploy v Travisu, tak se mi při updatu appky akorát nastaví verze, nic víc.

**Comment by Halama** [comment]
btw. k cemu se tam zadava ten region? pracuje se s nim nekde? nikdy jsem ho nevyplnoval.

**Comment by ondrejhlavacek** [comment]
https://developers.keboola.com/extend/registration/deployment/#step-2-----add-deploy-script je uvedenej deploy skript, co URI nastaví. Měl jsem starou verzi deploy scriptu, ale v UI by to teda asi být nemuselo a měl by tam být link na deploy dokumentaci?

**Comment by odinuv** [comment]
z UI bych to nemazal, ale urcite by se to melo vic schovat a asi bych to nalinkovani na deploy script dal uz sem https://github.com/keboola/developer-portal-ui/issues/341 protoze to je ten moment kdy s tim zacit

**Comment by JakubMatejka** [comment]
Není to spíš do ui? http://github.com/keboola/developer-portal-ui/issues Nebo je na tom blbě něco z hlediska API?

**Comment by odinuv** [comment]
presouvam do UI https://github.com/keboola/developer-portal-ui/issues/395
