### ISSUE TITLE
Allow `none` as stagingStorageInput value

### ISSUE THREAD

**Issue by ErikZigo** [keboola/developer-portal#164]
Docker runner podporuje nový typ input stagingu `none`
https://github.com/keboola/docker-bundle/issues/165

Zatím pro to nemáme oporu v developer portalu a jeho ui

**Comment by JakubMatejka** [comment]
https://github.com/keboola/developer-portal/pull/165
Jdu na to. Vypadá to dobře, díky.

**Comment by JakubMatejka** [comment]
Hotovo, za chvíli to bude v produkci. https://github.com/keboola/developer-portal/releases/tag/2.32.0
