### ISSUE TITLE
Wrong password message is not clear enough / Do not limit characters in password

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#167]
Related to #149 

I bumped to this again. I added space to password and error message is saying my password is not valid - and mentioning nothing about space/whitespace/empty char.

![screenshot_2017-12-01_18-01-51](https://user-images.githubusercontent.com/419849/33493864-bc9e1824-d6c1-11e7-95ea-9d60f405e8ba.png)

My suggestion is to NOT limit any characters in password. Or, at least,  provide more clear message what password can contain.

**Comment by JakubMatejka** [comment]
To aws, já za to nemůžu. ;o) Ani to nejde povolit. Zprávu upravím.

**Comment by JakubMatejka** [comment]
Tak přece jen: https://github.com/keboola/developer-portal/commit/799c15f2ed0ee17be6cb933f8911f5c360a22029. Je to v Travisu
