### ISSUE TITLE
Stack-specific Parameters

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#169]
U každý appky bude nový parametr `stackParameters`, kde se budou ukládat parametry specifický pro daný stack. Mergovat se budou v sync skriptu přes deep merge do `image_parameters`.

```
{
    ...,
    "stackParameters": {
        "connection.keboola.com": {
            "#encrypted": "encrypted_us"
        },
        "connection.eu-central-1.keboola.com": {
            "#encrypted": "encrypted_eu",
            "nested": {
                "key": "value"
            }
        },
    },
    ...
}
```

via https://keboola.slack.com/archives/C1G9B2XMW/p1512388069000022

Docker Runner, potažmo šifrovací komponenta, nebude muset řešit ukládání vic hodnot (https://github.com/keboola/docker-bundle/pull/219)

**Comment by JakubMatejka** [comment]
Fixed in https://github.com/keboola/developer-portal/releases/tag/2.33.0.
Teď teda bude třeba upravit ui a sync skript v KBC.
