### ISSUE TITLE
List users api call broken

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#170]
According to documentation, if we want to list all users we should call:

https://kebooladeveloperportal.docs.apiary.io/#reference/0/admin-users/list-users

`GET https://apps-api.keboola.com/admin/users`

And expected response is array of users:

```json
[
  {
    "username": "test@keboola.com",
    "name": "Test User",
    "createdOn": "",
    "vendors": [
      "keboola"
    ]
  }
]
```

Unfortunately, the list users API call returns:

```json
{
  "email": "vlado@keboola.com",
  "name": "Vladimír Kriška",
  "vendors": [
    "keboola",
    "ujovlado",
    "fisa",
    "keboola-test"
  ],
  "isAdmin": true
}
```

**Comment by ujovlado** [comment]
Looks like is's returning a result of `GET https://apps-api.keboola.com/auth/profile`

**Comment by JakubMatejka** [comment]
Jo, týká se to všech admin callů co něco dělaj s userama. Vypisoval se výsledek autentizace a lambda dost zvláštně chcípla na následným promisu aniž by to vybublalo a vyfailovalo. Může za to chybějící `() =>` tady: https://github.com/keboola/developer-portal/commit/01263feeb0b491e79eb662d0cb212bcaec935793#diff-f813bc91f055bb95a955f45d61be3bf8R28 (ještě jsem to při debugu trochu zrefaktoroval, tak je tam těch úprav víc). Je to v travisu
