### ISSUE TITLE
Admin: Allow update user

### ISSUE THREAD

**Issue by pivnicek** [keboola/developer-portal#171]
If a user needs their phone or email changed, it would be good to be able to update the user's attributes.

https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-update-user-attributes.html

**Comment by JakubMatejka** [comment]
When the software MFA gets to the ui, we will deprecate sms MFA, so the phone won't be needed anymore. And it is not possible to change email because it is used as user id. So I close the ticket for now.
