### ISSUE TITLE
Add link to src repository

### ISSUE THREAD

**Issue by odinuv** [keboola/developer-portal#173]
add field to app where the link to git repository will be stored, the reason is having a backlink from application in dev portal to its source code, now we have only the docker image and there is no way to trace it to the actual code. 
This is for component author, so the link may be even a link to private repo which we can't access, but still can be used by the app author, or his successor to trace the application code

**Comment by JakubMatejka** [comment]
Fixed in https://github.com/keboola/developer-portal/releases/tag/2.36.0
