### ISSUE TITLE
Get MFA settings in user profile

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#174]

**Comment by ujovlado** [comment]
@JakubMatejka nevies nahodou, ci tato informacia bude dostupna aj v tokene?

**Comment by JakubMatejka** [comment]
@ujovlado tak to pochybuju, není tam ani plno dalších věcí (který teda nepotřebujem)

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/developer-portal/releases/tag/2.38.0

**Comment by JakubMatejka** [comment]
Property `isMfaEnabled` v profilu https://kebooladeveloperportal.docs.apiary.io/#reference/0/auth/get-user-profile
