### ISSUE TITLE
Allow also filter by app in "List app changes" admin api call

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#175]
Bodlo by, keby v tomto API calle bola moznost prihodit filter poda apky.

https://kebooladeveloperportal.docs.apiary.io/#reference/0/admin-apps/list-app-changes

Napr. param `appId` alebo `app`:
- `https://apps-api.keboola.com/admin/changes?since=since&until=until&appId=keboola.ex-gmail`
- alebo `https://apps-api.keboola.com/admin/changes?since=since&until=until&app=keboola.ex-gmail`

Chcem to kvoli keboola/developer-portal-ui#379, kde by som to rad zobrazil pre konkretnu apku, nie globalne pre vsetko.

**Comment by ujovlado** [comment]
A este mi napadlo, ci by sa tam nemohli dat aj optional parametre `limit` a `offset` :)

**Comment by JakubMatejka** [comment]
@ujovlado Ten limit a offset by byl lepší než since a until? Oboje bych tam nenechával, maximálně bych to vyměnil.

**Comment by ujovlado** [comment]
Aha, tak to som asi vymyslel blbost ... myslel som to tak, ze si vyfiltrujem len konkretnu apku, povedzme data za posledne 2 mesiace a potom (ak ich je vela) si v tom mozem strankovat, resp. obmedzit pocet vratenych zaznamov.

Ale ak bude to filtrovanie na apku, tak tych zaznamov moc nebude. Takze na ten `limit` a `offset` kasli, sorry.

**Comment by JakubMatejka** [comment]
No problem.

Fixed by https://github.com/keboola/developer-portal/releases/tag/2.39.0
