### ISSUE TITLE
Authentication SMS

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#179]
`###### is your GitHub authentication code.`
vs
`Your authentication code for Keboola Developer Portal is ######.`.

To druhý mě nutí, abych otevřel detail sms, u GitHubu mi stačí vidět notifikaci. Maj to takhle udělaný všichni, včetně bank, krome Developer Portalu nemusím nikdy do detailu SMS (a bezpečnost si nastavím tím, že nechci vidět v notifikaci text zprávy).

**Comment by ujovlado** [comment]
SMSiek sa asi chceme zbavit. No ak sa to uz bude upravovat, rad by som tam potom videl aj text “This code is valid for XX seconds.” ... kludne az niekde na konci.

**Comment by JakubMatejka** [comment]
Asi bych to už nechal, protože softwarový mfa bude v ui co nevidět, ne? 😄 

(Jinak teda mám úplně opačnou zkušenost. Znám tak jednu službu, která dává kód na začátek, jinak všichni ostatní, včetně tří bank co máme, to posílaj úplně na konci ;o)

**Comment by ujovlado** [comment]
> Asi bych to už nechal, protože softwarový mfa bude v ui co nevidět, ne? smile

jo, uz som si to osahaval, coskoro to tam pribudne ;)
