### ISSUE TITLE
Records with empty component changes

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#181]
I see empty changes in some apps.

![screenshot_2018-02-15_10-48-47](https://user-images.githubusercontent.com/419849/36250488-43726334-123e-11e8-8444-a74cd13f6c53.png)

Were those some internal changes we should hide?

I can filter this in UI very easily (diff btn is already hidden), but we should not return "change record" if there are no changes.

**Comment by JakubMatejka** [comment]
Ne, to se stane, když pošleš update, který nic nezmění (jako že chceš přepsat třeba název tím stejným). Už je to tady: https://github.com/keboola/developer-portal/issues/177 ale moc se do toho nehrnu, protože to není úplně triviální poznat. ;o)

**Comment by ujovlado** [comment]
Aha, sorry, o tom issue som vedel, no nejako som si to nespojil.
