### ISSUE TITLE
Return MFA authentication type in first login call response

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#182]
Could it be possible to return also "challenge" in the response of first login call?

Right now, the only way how to detect 2nd step is by checking message.

Current status:

```json
{
    "message": "Login with the session and your TOTP code",
    "session": "xyz"
}
```
or for SMS "Verification code has been sent to your mobile phone".

---

And I would like to have:

```json
{
    "message": "Login with the session and your TOTP code",
    "session": "xyz",
    "challenge": "SOFTWARE_TOKEN_MFA",
}
```
so I will decide what to display to user by challenge param.

**Comment by JakubMatejka** [comment]
Za chvilku to v bude v produkci (https://github.com/keboola/developer-portal/releases/tag/2.39.8)
