### ISSUE TITLE
Return challenge also in "get profile" api call

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#183]
It is great that from `/auth/profile` response I am able to get if user has MFA enabled or not.

But it would be usefull to have also type of the MFA setting there. Maybe value stored in  `PreferredMfaSetting` or simply `challenge` (with similar values as in `login` api call).

Example:

```js
email: "some@example.com"
isAdmin: false
isMfaEnabled: true
name: "Vladimír Kriška"
challenge: "SOFTWARE_TOKEN_MFA"
```
Or we can skip `isMfaEnabled` param and provide `only` challenge, which means that MFA is set.

---

Use case:

If user has SMS MFA (which is deprecated) I want to display warning and provide migration to SW MFA.

**Comment by JakubMatejka** [comment]
Ok, přidal jsem tam property `mfa`. Pokud ho uživatel nemá, tak je `false`. To `isMfaEnabled` tam zůstalo jako deprecated a odstraním ho pak s těma smskama. (https://github.com/keboola/developer-portal/releases/tag/2.40.0)
