### ISSUE TITLE
"Configuration description" preview is not working

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/developer-portal#194]
![image](https://user-images.githubusercontent.com/642928/39184806-29f57f56-47c5-11e8-9a80-91a9fc76c6b4.png)
![image](https://user-images.githubusercontent.com/642928/39184823-35356aac-47c5-11e8-9006-b03fb854d1a6.png)

**Comment by ujovlado** [comment]
Pls, report here https://github.com/keboola/developer-portal-ui
