### ISSUE TITLE
Component features

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#196]
https://keboola.slack.com/archives/C1G9B2XMW/p1525256271000467
https://keboola.slack.com/archives/C1G9B2XMW/p1525256381000192

**Comment by ondrejhlavacek** [comment]
UI k tomu asi netřeba a pro https://github.com/keboola/docker-bundle/issues/198#issuecomment-387721637 bych implementoval inverzí featuru, tj.

- všem existujícím komponentám se nastaví featura
- nové komponenty jí dostávat nebudou
- existujícím komponentám se bude postupně odebírat

klíčový je, aby ta featura byla nastavená před deployem docker runneru

**Comment by JakubMatejka** [comment]
@ondrejhlavacek Takže to pojmenujeme `features` a bude to pole. A po nasazení se jednorázově sqlkem přidá jedna featura všem existujícím komponentám, ok?

**Comment by ondrejhlavacek** [comment]
tak jo, super, díky!
