### ISSUE TITLE
Fix docs about `stackParameters`

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#199]
https://github.com/keboola/developer-portal-ui/issues/480#issuecomment-389211281

I can send PR for this later

**Comment by ujovlado** [comment]
No je tam napisane, ze to nemoze byt menene normalnym userom. T.j. ze to asi mozu len admini. Ale ide to pre vsetkych. Prave to sme fixovali na UI.

**Comment by JakubMatejka** [comment]
A jo, už to vidím, je to schovaný v popisku modelu. V parametrech update callu to normálně je
