### ISSUE TITLE
Image consistency check

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#203]
## Problém

Aktuálně evidujeme pro každou appku repository (ECR) a tag. Pokud se tag změní releasuje se nová verze appky. Bohužel teď ale nedokážeme detekovat že pod daný tag nebylo pushováno opakovaně.
Souvisí to se schvalováním jednotlivých verzí appek non-trusted vendorů #200 

## Možné řešení
Pokud bysme u appky navíc vyžadovali `digest` a ten používali při [spouštení](https://docs.docker.com/engine/reference/run/#imagedigest) nebylo by možné appku měnit aniž by to šlo přes developer portal.

### Flow
- Při [update app](https://kebooladeveloperportal.docs.apiary.io/#reference/0/app/update-app) a změně tagu se k nově vznikající verzi aplikace uloží digest nového image/tagu který se stáhne z ECR API. Tím se zároveň i ověří že je pushnutý.
- Docker runner bude při spouštění image využívat digest appky (`docker run keboola/processor-create-manifes@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0`) místo tagu pokud bude digest k dispozici.
  - ~~Nebo pullne image s tagem a ověří jeho digest před samotným spuštěním~~

**Comment by tomasfejfar** [comment]
> V moment releasu komponenty developer (ci) pošle kromě nového tagu i aktuální digest image který pushnul.

Jako lepší řešení by mi přišlo si to udělat na stran dev portálu. 

* developer pošle tag
* my si ho pullneme
* zjistíme si z něj digest a ten si uložíme

Když budou devs posílat tag i digest, tak hrozí, že se to rozuteče, pošlou špatný, který nebude sedět k tagu, atp. IMO

**Comment by odinuv** [comment]
tak bych byl pro to resit to na strane devportalu - pri spusteni jobu je to zbytecnej overhead,
podle me staci akorat pri updatu appky v devportalu overit `if oldtag == newtag and olddigest =! newdigest then fail`
developer nemusi digest posilat, protoze image uz je v repozitari pushnuty - cili se na nej devportal muze sam zeptat (credentials ma)

**Comment by Halama** [comment]
to je blbost ne? chceme osetrit situaci kdy tam pak pod stejny tag pushne neco jineho

**Comment by odinuv** [comment]
no vsak - pokud je tag stejny a digest jiny, tak to rejectnem

**Comment by Halama** [comment]
ale on prece vubec nemusi komunikovat z dev portalem

**Comment by odinuv** [comment]
jo aha, jasne, je to blbost :) my nebudem mit ten starej tag, kdyz ho prepise

**Comment by Halama** [comment]
vyzada si od nej credentials, to je ale vse pak uz rovnou pushne

**Comment by Halama** [comment]
takze bud jak jsem psal ja, nebo jak rika tomas. Kazdopadne musi byt ulozeny digest a ten se bude poustet.

**Comment by odinuv** [comment]
co treba si to jeste nejak otagovat pri nasazeni - "production" ?

**Comment by Halama** [comment]
bojim se ze nedokazeme zamezit push takoveho tagu bokem, by to muselo byt uplne jine repo

**Comment by Halama** [comment]
ty tagy jsou ted ciste v rezii developera

**Comment by Halama** [comment]
prijde ti neco blbeho na tom digestu? me akorat to ze pri spusteni nemuzes rict zaroven tag i digest (jakoze digest pro kontrolu). Proto jsem jako druho variantu zminoval ten check za behu.

**Comment by Halama** [comment]
^ a resim to kvuli tomu vystup jobu ze ted tam mame tag i digest. to by tam vlastne ale mohlo byt porad ne?

**Comment by odinuv** [comment]
jj, no mozna by to nakonec bylo nejlepsi mit kopii
jak rika tf - pokud bude developer posilat i digest, stejne nemas zaruku, ze to je spravnej digest (notabene je nemozny ho zjistit pred pushnutim do repozitare, protoze image hash != registry digest)

**Comment by Halama** [comment]
jo pushne a pak ten digest posle do appky. my muzem i overit ze sedi. Nikdy nemuzes vedet co tam pushnuje, tohle jenom zajisti ze se to nezmeni.

**Comment by Halama** [comment]
nebo fakt to asi proste muze ten aktualni digest sosnout z ECR v moment kdy updatuje tag/image appky a je to?

**Comment by Halama** [comment]
na smazani image nema prava. Me porad ten digest jako jednozna identitikace immutable veci prijde fajn. Ten problem ze se ti nespusti nic jineho nez tam prislo v moment update app to splnuje, jak se stavet k tomu co prijde v moment update app ted neresim.

Porad vychazim z toho ze chceme schvalovat verze applikaci, tak mi prijde blby kdyz by to kdokoliv mohl obchazet. Uz si ale moc nepamatuju jaka byla motivace za tim schvalovanim viz #200

**Comment by odinuv** [comment]
blby je, ze kdyz ta kontrola bude pri spusteni, tak kdyz pushnes blbe otagovanej image, tak ta komponenta nepujde spustit, takze se rozjebe produkce (cili zase museli bysme spoustet starej digest)

motivace za schvalovanim je, ze zarucime, ze ta vec dela to co ma (cili kdyby vyvojarovi XY ruplo v kouli a a chtel krast data, tak to pres nas neprojde), pokud bysme meli tohle zaridit - tak musime resit ten digest,  cili jestli mame resit tohle, tak bych nejradsi pridal do definice komponenty novou property `runable-digest` a ten spoustel (a potom muze devportal resit to, ze pokud `new tag == old tag` && `new digest != old digest` tak runnable digest nezaktualizuje a skonci s nejakym srozumitelnym errorem

**Comment by Halama** [comment]
nejak tomu nerozumim hlavne tomu porovnavani pri updatu app...
ta kontrola pri spusteni je teda blbost, to byla jen varianta a fakt by to pushem neceho to stejneho tagu rozbil:)

Proste to priradi verzi appky digest ktery bude spoustet, a tim je to navzdy zafixovany. Verze appky zmenit nejde a digest ukazuje vzdy na stejny image.
Kdyz bude vyvojar chtit releasnout novou verzi pushne ji pod novym tagem a zavola update v dev portalu, tim vznikne nova verze ktera bude ke schvaleni. V ten samy moment se k ni ulozi digest z ECR a zaroven to tim zkotroluje ze to skutecne pushnul.

**Comment by odinuv** [comment]
jo to je jednodussi

**Comment by Halama** [comment]
updatnul jsem záhlaví

**Comment by tomasfejfar** [comment]
Já si pořád nejsem jistý, jestli to správně chápu. A přijde mi to pořád nějaké zbytečně složité. Zkusím za sebe napsat jak si myslím, že to může fungovat (snad je to to na čem jsme se teď shodli). 

* jako developer pushnu nový image do ECR (je v praxi jedno jaký, jestli tag nebo sha256) v rámci deploy scriptu
* na konci deploy scriptu se zavolá `update-app-repository ${KBC_DEVELOPERPORTAL_VENDOR} ${KBC_DEVELOPERPORTAL_APP} ${TRAVIS_TAG} ecr ${REPOSITORY}`
* devportál v rámci handlingu toho volání udělá `docker pull ${REPOSITORY}:${TRAVIS_TAG}` (resp. [zavolá API](https://forums.docker.com/t/get-image-digest-from-remote-registry-via-api/9480))
* ze staženého image vytahne digest
* digest uloží jako novou verzi aplikace (tj. ke schválení)
* když někdo aplikaci publishne, do KBC se deployuje digest

To je happy path. A teď potenicální problémy a jak se to chová:

* někdo pushne do ECR pod tím samým tagem nový image (mimo deploy)
  * nic se nestane, protože se nevolá update v dev portálu
* někdo pushne do ECR pod tím samým tagem nový image (v deploy scriptu)
  * propadne to dev portálem, docker pull, stahne se nový image, vytahne se nový digest → ~ happy path
* někdo smaže ten původní digest z ECR
  * jde to do kopru, protože se nedá najednou pullnout ta komponenta
  * *a to je správně*
  * doteď to prostě tiše vezme jiný image

**Comment by Halama** [comment]
Teď jsi to ale právě zkomplikoval, ten docker pull je zbytečný protože digest vrátí ECR takže:

- jako developer pushnu nový image do ECR (je v praxi jedno jaký, jestli tag nebo sha256) v rámci deploy scriptu
- na konci deploy scriptu se zavolá update-app-repository ${KBC_DEVELOPERPORTAL_VENDOR} ${KBC_DEVELOPERPORTAL_APP} ${TRAVIS_TAG} ecr ${REPOSITORY}
- devportál v rámci handlingu toho volání update-app uloží digest nového image/tagu který se stáhne z ECR API. Tím se zároveň i ověří že je pushnutý.
- Docker runner bude při spouštění image využívat digest appky (docker run keboola/processor-create-manifes@sha256:9cacb71397b640eca97488cf08582ae4e4068513101088e9f96c9814bfda95e0) místo tagu pokud bude digest k dispozici.

**Comment by Halama** [comment]
resp. přijde ti složitá i tahle varianta?

**Comment by JakubMatejka** [comment]
Stažení a uložení digestu by se teda mohlo udělat při tý publikaci, když se teď bude publikovat každá verze. Pokud se tag nenajde v repository, tak publikace vyfailuje. A to je teda vlastně všechno, co se bude dít na straně Portálu, chápu to dobře?

**Comment by Halama** [comment]
Myslím si že by se to mělo udělat spíš v moment toho updatu at je to ihned spárované s tou verzí.

**Comment by Halama** [comment]
jinak to souhlasí že na straně dev portalu by to mělo být vše.

**Comment by tomasfejfar** [comment]
Určitě by to mělo být v tu chvíli, kdy zavoláš `update-app-repository`. To je ta chvíle, kdy oznamuješ, že "tohle se bude deployovat". Kdykoli později tam dělá prostor pro race condition, kdy to mezitím někdo může updatnout.

**Comment by JakubMatejka** [comment]
Takže při každým updatu appky, když se mění něco v `repository`? (https://kebooladeveloperportal.docs.apiary.io/#reference/0/app/update-app)

**Comment by JakubMatejka** [comment]
- Co se má stát ve chvíli, když údaje k repozitáři nebudou obsahovat validní informace (tj. třeba uživatel mění repo z Dockerhubu na Quay, změní `type` a zapomene změnit `uri`)? Má se digest nechat prázdný, nebo odmítnout změny uložit?
- Co privátní repozitáře? Dívám se, že některý mají heslo enkryptovaný pro komponentu, k tomu se nedostanu. (nebo se dá digest zjistit i bez hesla?)
- Pak jsou tam komponenty, co nemají repository vůbec, zejména asi `application`s (a potom třeba i `keboola.csv-import`, `wr-portal-sas`, `keboola.wr-mode`), ty mají v digestu vrátit jen `null` a víc neřešit?
- Co `reporitory.type=builder`, taky vracet v digestu `null`?

**Comment by Halama** [comment]
Řešil bych to jenom pro naše ECR. Vše ostatní bude imho brzy deprecated ne?
Všude jinde `null`

**Comment by JakubMatejka** [comment]
ok, viz. https://github.com/keboola/developer-portal/pull/226

**Comment by JakubMatejka** [comment]
Up and running <img width="389" alt="apps 2018-08-27 10-38-08" src="https://user-images.githubusercontent.com/215660/44649847-5563aa00-a9e5-11e8-921e-9a1b094e7f01.png">
