### ISSUE TITLE
Vymena fontu

### ISSUE THREAD

**Issue by janmichek** [keboola/developer-portal#205]
V KBC se nam to pomalu rysuje.
V Developer portalu bychom radi videli jak vypada kombinace fontu Whitney a Gotham.
Ve finale to nemusi byt implementovany = nemusi kazda nase aplikace mit uplne stejnou kombinaci fontu, ale logicky se nabizelo to vyzkouset. 
S Jackem jsme mrkli na uvodni stranku a tady jsou navrzene zmeny.

![bez-nazvu-1](https://user-images.githubusercontent.com/15363559/40730632-677dab42-642f-11e8-9a18-3db3d861632d.gif)

JEste presne nevime jak prancovat s tensimy nadpisy (gotham) a s boldovanym normalnim textem (whitney). Idealne pokud to budeme drzet minimalisticky.

Core stylu ktery se chystame implemenotvat v kbc je nasledujuci - zkusil bych tenhle snippet jako odrazovy mustek v devportalu + nejake upravy.

```
body, .label, .badge {
  font-family: "Whitney SSm A", "Whitney SSm B";
  font-style: normal;
  font-weight: 400;
}

h1, h2, h3, h4, h5, h6 {
  font-family: "Gotham Rounded A", "Gotham Rounded B";
  font-style: normal;
  font-weight: 700;
}
 .btn {
  font-family: "Gotham Rounded A", "Gotham Rounded B";
  font-style: normal;
  font-weight: 500;
}
```

Nahraj nam sem potom prosim screeny.

**Comment by ujovlado** [comment]
tutok -> https://github.com/keboola/developer-portal-ui ;)

**Comment by janmichek** [comment]
ups, presunuto https://github.com/keboola/developer-portal-ui/issues/483
