### ISSUE TITLE
Component complexity / ease of setup

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#206]
https://github.com/keboola/kbc-ui/issues/1734#issuecomment-393277564

- easy / medium / hard

The only question is where to store these values. Component "enum" property or `uiOptions`?

I'd rather prefer new property since only one of them should be selected.

**Comment by odinuv** [comment]
nebo features? otazka je, jestli nechame kohokoliv aby to nastavoval. Ja bych byl spis pro to, abysme to nastavovali my, po zrale uvaze, nez aby si to delal autor komponent v navalu euforie (coz vylucuje uioptions)

**Comment by ujovlado** [comment]
Myslim, ze je to na nas. Idealne keby to clovek zdetegoval pri schvalovani komponenty  a doplnil to tam.

**Comment by odinuv** [comment]
timpadem admin only a asi nova prop

**Comment by JakubMatejka** [comment]
default je `null`?

**Comment by odinuv** [comment]
jo

**Comment by ujovlado** [comment]
Ano, komponenta to nemusi mat nastavene

**Comment by JakubMatejka** [comment]
viz. https://github.com/keboola/developer-portal/pull/214

**Comment by janmichek** [comment]
Jenom chci ze zvedavosti checknout v jakym je to stavu? Nejak to nemuzu dohledat, visi mi v todocku UI cast

**Comment by odinuv** [comment]
je to mergnuty a closnuty, takze ti to visi v todocku kbc ui spravne, mas to udelat :)

**Comment by janmichek** [comment]
ok, cool. Zitra na tom zacnu
