### ISSUE TITLE
component type: transformation

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#207]
měnil jsem něco v UI pro `keboola.r-transformation` a nedovolilo mi to uložit, tak jsem musel změnit typ na `application`, i když to má být `transformation`. nedovolilo mi to pak ani změnit přímo přes API

**Comment by odinuv** [comment]
nema to by other? to jde nastavit pres api

**Comment by ondrejhlavacek** [comment]
hm! jo! python transformace je v other. tak to zatím přepnu na other přes api a transformace vyřešíme později

**Comment by ondrejhlavacek** [comment]
@odinuv jaks to prosimtě přes api udělal?
`PATCH https://apps-api.keboola.com/admin/apps/keboola.r-transformation`
```
{"errorMessage":"Parameter type must be one of: extractor, application, writer, processor","requestId":"04481d48-6fc7-11e8-8fa5-97505395b054"}%  
```

**Comment by odinuv** [comment]
aha, ty jo no to nevim sakra, pamatuju si, ze se me to taky stalo a neslo me to spravit, mel jsem pocit, ze pres API to slo.
Mozna jsem udelal rollback na verzi kde to bylo a potom z ni znovu patch pres API?

**Comment by odinuv** [comment]
nemuzu to najit v historii

**Comment by ErikZigo** [comment]
https://github.com/keboola/developer-portal/issues/204

**Comment by ondrejhlavacek** [comment]
aha, rollback a pak patch jen na vybraný parametry. tak na to teď asi prdím :-)

**Comment by JakubMatejka** [comment]
Stačí teda other, či čo?

**Comment by ondrejhlavacek** [comment]
Dal bych oboje, transformation se bude hodit v budoucnu?

**Comment by JakubMatejka** [comment]
To nevím, transformace se budou vydávat jako komponenty?

**Comment by ondrejhlavacek** [comment]
Bylo by to super, už jsme se o tom párkrát bavili. Ale zatím se nic neděje,
tak se developer portal může upravit až to nastane

**Comment by JakubMatejka** [comment]
Já bych si na to počkal ;o)
