### ISSUE TITLE
Could not accept invitation to vendor after removal and another invite

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#208]
How to simulate:

- login
- invite user to your vendor
- (user receives an email)
- (user confirms it)
- delete user from you vendor
- invite user to your vendor
- (user receives an email)
- (user cannot confirm it) -> error "You have already accepted the invitation"

**Comment by JakubMatejka** [comment]
viz. https://github.com/keboola/developer-portal/pull/223
