### ISSUE TITLE
Error when accepting invitation

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#222]
https://keboola.zendesk.com/agent/tickets/8710

How to simulate:
- login
- invite brand new developer (without account in devportal)
- in invitation email there's a link to "accept invitation"
- clicking on the link "throws" app error

What is weird I cannot see the trace of this err

**Comment by ujovlado** [comment]
I can confirm it happened also for my account.

And I found a problem:


```
Jul 02 19:11:58 developer-portal-v2 prod:  {"event":{"requestId":"***","function":"developer-portal-v2-prod-vendors","httpMethod":"GET","path":"/vendors/ujovlado/invitations/vlado+test5@keboola.com/***","apiRequestId":"***","ipAddress":"***","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36"},"statusCode":404,"error":"User account does not exist. Please signup first."} 
```

**Comment by ujovlado** [comment]
I didn't know user has to exist in devportal before one can invite him to join vendor. Is it new?

**Comment by JakubMatejka** [comment]
Ne to ne, mělo by se to odchytit tady: https://github.com/keboola/developer-portal/blob/aeb0a8bc94de3fee63ccf09fd2059720312aff45/src/app/vendor.js#L144-L153
Zřejmě v Cognito změnili `err.code`, nebo co?

**Comment by JakubMatejka** [comment]
Tvl, WTF? Code je pořád `UserNotFoundException`. Ze zoufalství jsem tam dal i console.log na ověření a najednou to prošlo. Nic víc jsem v tom neměnil ;o) (na develu na https://qvk10jnae0.execute-api.eu-west-1.amazonaws.com/dev/vendors/keboola/invitations/testxx+jakub@keboola.com)
<img width="642" alt="vendor js developer-portal 2018-07-02 20-12-15" src="https://user-images.githubusercontent.com/215660/42179488-7f1f38d2-7e34-11e8-993a-98d425d40561.png">

**Comment by ujovlado** [comment]
Pockat, nekukas ale inde? to bol prave `GET` request.
```
https://apps-api.keboola.com/vendors/ujovlado/invitations/vlado+test5@keboola.com/52f7c281-a6e4-4e02-8f61-3f8573083c63
```

**Comment by JakubMatejka** [comment]
No jo ;o) Tak to jo, to tam bylo vždycky. Ani to jinak nejde, potřebuje account v Cognito. Akorát se to někde neodchytí jako user error, to pořeším

**Comment by ujovlado** [comment]
Tam by mozno stacilo zobrazit tu html stranku co si zacal prerabat a len mu tam napisat "signup, the come back" ;)

**Comment by ujovlado** [comment]
Tym myslim naviest ho aby sa regol a potom to skusil z emailu akceptovat znovu. Je to trosku tazkopadne ale co uz

**Comment by ujovlado** [comment]
No asi by stacilo pridat tam link na: https://components.keboola.com/auth/create-account
