### ISSUE TITLE
Lock ECR permissions

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#228]
Allow ECR operations only on dev portal prefix.

- Lambda Role https://github.com/keboola/developer-portal/blob/0bff6178b6800261710fa4401e009e522f99a28f/serverless.yml#L540
- ECR Role for credentials provider https://github.com/keboola/developer-portal/blob/0bff6178b6800261710fa4401e009e522f99a28f/serverless.yml#L570

**Comment by Halama** [comment]
reference https://keboola.slack.com/archives/C1G9B2XMW/p1531900828000409

**Comment by JakubMatejka** [comment]
viz. https://github.com/keboola/developer-portal/pull/229
