### ISSUE TITLE
Add Sydney stack

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#242]
`connection.ap-southeast-2.keboola.com`

![image](https://user-images.githubusercontent.com/497675/45081034-91d68a80-b0f6-11e8-9079-6ce51ce262ae.png)

**Comment by ondrejhlavacek** [comment]
V dokumentaci nevidím api call na přidání stacku

**Comment by JakubMatejka** [comment]
API call zatím není, Sydney jsem přidal do db.

**Comment by ondrejhlavacek** [comment]
Dík!
