### ISSUE TITLE
Application type transformation

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#243]
Nemůžu přes API updatnout transformace.
```
➜  ~ curl --include \
     --request PATCH \
     --header "Content-Type: application/json" \
     --header "Authorization: ..." \
     --data-binary "{
    \"type\": \"transformation\"
}" \
'https://apps-api.keboola.com/admin/apps/transformation'
HTTP/1.1 422 
...

{"errorMessage":"Parameter type must be one of: extractor, application, writer, processor, other","requestId":"bb0e32fd-b28e-11e8-af6c-4f7b34d44110"}
```

**Comment by JakubMatejka** [comment]
Hmm, a je to vůbec k něčemu potřeba? S tímhle typem jsou tam jen dvě appky (`transformation` a `transformation-new`) a asi nehrozí, že by měly přibývat další. Nestačil by `other`?

**Comment by ondrejhlavacek** [comment]
V budoucnu určitě budou, jak se transformace roztrhnou na vlastní appky. teď to asi můžem nechat bejt, jenom se transformace nesmí upravovat přes UI. Other se tam nastavit nesmí, rozbije to routing na frontendu.
