### ISSUE TITLE
Describe better what is License and what it's supposed to do

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/developer-portal#255]
Ref.: https://keboolaglobal.slack.com/archives/CBX9MB2NT/p1538822870000100

Even I misunderstood that it's not enough to give it MIT and be done with it (although that's what some components like [aws-s3-extractor in docs example](https://developers.keboola.com/integrate/storage/api/configurations/) or [azor.ex-azor](https://components.keboola.com/components/azor.ex-azor) do).

I think it should be enough to add longer description to the field. Also it might be helpful to add a page to documentation describing how such license is supposed to look and maybe add a generic license for extractors, apps and writers.

**Comment by tomasfejfar** [comment]
I created a new issue in docs instead, but I still think `This should not be the license you add to your code, but rather something regarding data, etc.` in field's description would be helpful.

**Comment by tomasfejfar** [comment]
Link to the newly created docs section would be enough ;)

**Comment by JakubMatejka** [comment]
Isn't it rather a ui issue (keboola/developer-portal-ui)?

**Comment by tomasfejfar** [comment]
D'oh! I close this one and add a note to the docs only.
