### ISSUE TITLE
Weird response for changes in admin section

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#271]
![screenshot_2018-12-07_20-19-56](https://user-images.githubusercontent.com/419849/49668121-7b293200-fa5d-11e8-9644-05540591815b.png)

![screenshot_2018-12-07_19-52-32](https://user-images.githubusercontent.com/419849/49668130-7fede600-fa5d-11e8-8f29-05d771c91e92.png)

Related to: https://github.com/keboola/developer-portal-ui/issues/556 (cc @odinuv )

**Comment by ujovlado** [comment]
In very component there is:

- createdBy `support@keboola.com`
- createdOn `09/01/2017, 10:42`

**Comment by JakubMatejka** [comment]
Nó, to je datum vytvoření komponenty. Pokud hledáš datum vytvoření verze, tak to je v `updatedOn`. Nebo to blbě chápu?

**Comment by ujovlado** [comment]
No ale nefungovalo to doteraz (resp. neviem dokedy inak?)

UI je naimplementovane tak ako vidno tu: https://github.com/keboola/developer-portal-ui/issues/556#issue-388771086

T.j.:

- api response vracala pole zmien (v tomto pripade obmedzenych na konkretnu komponentu)
- ^ kazda z tych zmien mala `createdOn`, `createdBy` a changes -> t.j. kedy, kto a ake atributy zmenil
- ^ a v poli `changes` boli zmeny jednotlivych atributov (meno, popis, stara hodnota, nova hodnota)

**Comment by ujovlado** [comment]
Tu je screenshot, kde vidno ako to fungovalo: https://github.com/keboola/developer-portal-ui/pull/411#issuecomment-363068069

![screenshot_2018-02-05_13-13-45](https://user-images.githubusercontent.com/419849/35804091-8d6f5bb0-0a76-11e8-8083-2efc86b2fc3b.png)

**Comment by JakubMatejka** [comment]
Ajaj, kua, to jsem teda nejspíš rozbil tímto: https://github.com/keboola/developer-portal/pull/246 ;o( Bude to teda třeba upravit v ui

**Comment by ujovlado** [comment]
Neviem, moc sa mi to upravovanie v UI nepaci. API zacalo davat ine data, malo by sa to upravit tu. Imho sa k tomu musime stavat rovnako ako ked by sme nieco zmenili na API, ktore pouziva nejaky klient - nepovies mu "preprogramuj si to, zmenili sme response".

**Comment by JakubMatejka** [comment]
To chápu no, ale co teda navrhuješ? Byla to dost velká, vlastně BC-break změna s tím, že se přestala používat db tabulka `apps` a všechno je v `appVersions` a je to vyčleněná přípava na tu čekající změnu schvalování. 

V detailu appky je to asi jasný, tam by `createdOn` mělo být datum vytvoření první verze. Ale ve výpisu verzí to mám v SELECTu přejmenovat z `updatedOn` na `createdOn`?

**Comment by ujovlado** [comment]
Ta uprava by nemal byt zlozita. Vcera som sa v tom trosku vrtal, rozbehal som si to s pomocou serverless-offline a trosku ladil tu funkciu`adminListChangesAcrossApps`.

Zda sa mi to tam trosku zvlastne - vytahuju sa tam vsetky verzie (podla kriterii) a potom este pre kazdu robi separatna query na ziskanie predoslej verzie. Je to tam potom samy Promise :). Na druhu stranu to celkom chapem, pokial sa nejedna o zmeny konkretnej apky, neviem si (zatial) moc predstavit ako to ziskat na jeden dotaz. Keby to bolo vzdy len o jednej apke, vyriesil by to pekny UNION ALL, kde by sa pridala len predosla verzia. To je ale na iny PR, mozno sa v tom povrtam.

K veci. Staci ak `changedOn` a `changedBy` zacnu vracat relevantne udaje, zvysok by mal ostat bezozmeny.

Navrhoval by som na uvod nieco taketo:

```diff
diff --git a/src/app/app.js b/src/app/app.js
index 586750d..3cc6fe6 100644
--- a/src/app/app.js
+++ b/src/app/app.js
@@ -161,13 +161,19 @@ export default class App {
             .then((prev) => {
               const prevCopy = prev ? _.cloneDeep(prev) : {};
               const nextCopy = app ? _.cloneDeep(this.dbApps.constructor.formatAppOutput(app)) : {};
+
               delete prevCopy.version;
               delete prevCopy.createdBy;
               delete prevCopy.createdOn;
+              delete prevCopy.updatedOn;
+              delete prevCopy.updatedBy;
               delete prevCopy.vendor;
+
               delete nextCopy.version;
               delete nextCopy.createdBy;
               delete nextCopy.createdOn;
+              delete nextCopy.updatedOn;
+              delete nextCopy.updatedBy;
               delete nextCopy.vendor;
               const changes = [];
               _.forIn(prevCopy, (val, key) => {
@@ -200,8 +206,8 @@ export default class App {
 
               resolve({
                 id: app.id,
-                createdOn: app.createdOn,
-                createdBy: app.createdBy,
+                createdOn: app.updatedOn,
+                createdBy: app.updatedBy,
                 changes,
               });
             })));
```

No a druhy bug je, ze do diffu dava obcas aj veci ktore sa nezmenili. To mozeme ale poriesit v separatnom PR ked tak.

Poslem PR na obe veci, tam to mozeme doladit.
