### ISSUE TITLE
Integrace do connection 

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#34]
V tuhle chvíli máme developer portal s API http://docs.kebooladeveloperportal.apiary.io/#reference/0/public-api/get-app-detail

a současný seznam komponent https://connection.keboola.com/v2/storage

Ze seznamem komponent pracuje docker bundle, orchestrátor, uičko a asi další komponenty.

Seznam komponent obsahuje nejenom docker komponenty ale i komponenty typu transformací, gd-writeru nebo "fake" komponenty `keboola.ui-oauth-external`.
## Jak to napojit

Mají komponenty přistupovat přímo k developer portalu? Finálně asi ano nebo minimálne akceptovat jeho strukturu odpovědi. V tuhle chvíli by to ale znamenalo přepis všech komponent co se seznamem komponent (developer portálem) pracují.
Pokud by to pracovalo napřímo s developer portálem který pojede v jedné globální instanci tak může být i větší latence pro přístup např. z eu (tohle je dost minor issue).

Jako nejpraktičtější mě proto napadá varianta kdy se jednotlivé instance kbc budou synchronizovat z developer portálem. Budou mít třeba minutový cron a prostě si k sobě kopírovat tohle http://docs.kebooladeveloperportal.apiary.io/#reference/0/public-api/list-published-apps a detaily appky. A pro zpětnou kompatibilitu pak z toho co si stáhnou budou generovat https://connection.keboola.com/v2/storage
## Otázky
- Co s non-docker komponentami (transformace, gooddata-writer, orchestrace) ?
- Co s fake komponentami. Asi je potřeba je projít a zjistit o co jde např. https://external.keboola.com/oauth/index.html#/?_k=f194ub asi stejně bude potřeba připravit pro každá region atd.

**Comment by JakubMatejka** [comment]
Pro ten importní skript by bylo dobrý se inspirovat tímhle skriptem, kterým jsem to naopak natahal z kbc: https://github.com/keboola/developer-portal/blob/master/scripts/import.js#L65 ;o) (a případně ho zkontrolovat jestli tam nemám nějakou chybu).

Non-docker komponenty mají v db vyplněný sloupec `legacyUri` (resp. mají ho tam všechny u kterých uri neodpovídalo formátu `syrup.keboola.com/docker/<appId>`)

Komponenty s flagem `excludeFromNewList` dostaly sloupec `isVisible=0`, tj. nejsou ve výpisu komponent (http://docs.kebooladeveloperportal.apiary.io/#reference/0/public-api/list-published-apps) a asi by bylo dobrý je projít a promazat ty co už nefungují

**Comment by Halama** [comment]
super to zni dobre. Pripravim teda ten sync command na strane KBC.

@JakubMatejka Koukam ze delas na to provisioning do AWS, dej pak prosim vedet az to bude ready zkusil bych si to nahodit.

**Comment by JakubMatejka** [comment]
Můžu tomu nějak pomoct na straně Connection? Klidně se do něčeho příští týden pustím

**Comment by Halama** [comment]
@JakubMatejka jj prave jsem si myslel ze by si mohl udelat ten command co to sosne z developer portalu do kbc. Domluvime se asi v pondeli nebo kdy ze dorazis:)
