### ISSUE TITLE
AWS ECR Support

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#39]
Ke komponentě by si uživatel mohl vytvořit AWS ECR repozitář pod naším accountem (je to spolehlivější než Docker Hub a Quay.io dohromady) a je to defakto zdarma a privátní. 

Představuju si to tak, že by Developer Portal vytvořil repozitář v ECR a pak dynamicky přes API call rozdával push oprávnění. Pull oprávnění budou globálně nastavený přes tag/usera instance workeru. 

Push oprávnění slouží k tomu, aby uživatel/CI skript deploynul novou verzi image do repozitáře. Mělo by to fungovat tak, že uživatel zavolá API call a dostane zpět `docker login` command pro příslušný repozitář (ekvivalent výstupu CLI commandu `aws ecr get-login`). V integračním skriptu pak nahradí tento řádek https://github.com/keboola/docker-demo-app/blob/1.1.7/deploy.sh#L26 voláním toho API a execováním commandu z odpovědi (nebo parametrů z odpovědi). Výhoda - nemusíme pro každý repo dělat účet a k těm účtům ukládat credentials do CI toolu, ale uloží se tam jen token do Developer Portálu, který vygeneruje dočasný credentials pro push.  

https://developers.keboola.com/extend/docker/tutorial/automated-build/#setting-up-a-repository-on-aws-ecr

https://sites.google.com/a/keboola.com/devel/kbc/docker#TOC-AWS-ECR

**Comment by JakubMatejka** [comment]
Je potřeba řešit ta oprávnění? Tady ta metoda vygeneruje push i pull oprávnění pro repozitář: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECR.html#getAuthorizationToken-property. Stačilo by to?

Udělal bych teda dva API cally, jeden na založení repozitáře a druhý na vygenerování toho tokenu. Jak bude vypadat `data.definition` pro docker runner? (resp. to co je v popisu komponent: https://connection.keboola.com/storage). Type `ecr`, uri `vendor/appId` a co tag, bude se nějak řešit?

**Comment by JakubMatejka** [comment]
Blbost, to je token pro celou registry (tj. celý účet), blbě jsem pochopil co se tím myslí. Tak to nic, stejně budu muset řešit, aby to byla práva jen pro konkrétní repository.

**Comment by ondrejhlavacek** [comment]
`data.definition`: 
```
{
    "type": "aws-ecr",
    "uri": "147946154733.dkr.ecr.us-east-1.amazonaws.com/keboola/docker-demo-app",
    "tag": "1.1.7"
}
```

Je potřeba, aby ten token měl oprávnění jen pro ten jeden konkrétní registr, což se dá určit v parametru toho api callu (`registryIds`). 

Ten API call může rovnou vrátit username/password pro `docker login` command, nebo může vrátit to, co vrací metoda `getAuthorizationToken` - to nechám na tobě, ten token je přesně `base64_encode($username . ":" . $password)`, takže není problém to kdekoliv dekódovat. Já bych se asi osobně klonil k tomu vrátit user/pass (bude to třeba jednodušší v travisu), ale nevím, jak moc futureproof to je (ale asi jo). 

Odpověděl jsem ti? :-)

**Comment by JakubMatejka** [comment]
No to právě ne, "registr" = celý aws account, my chceme jen práva na konkrétní repository (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECR.html#getAuthorizationToken-property). Ale už to mám rozpracovaný, vytvořím repozitář, roli pro ten repozitář a právě dělám na assumnutí té role a vygenerování tokenu.

**Comment by ondrejhlavacek** [comment]
No je ta role potřeba? Přes `registryIds` by to nešlo?

**Comment by JakubMatejka** [comment]
Tvl. tak tentorkát raději screenshot ;o))

<img width="1097" alt="class__aws_ecr_ _aws_sdk_for_javascript" src="https://cloud.githubusercontent.com/assets/215660/21308839/1436ba84-c5dc-11e6-9f04-bd21ad81aee2.png">

**Comment by JakubMatejka** [comment]
Nebo jinak: pomocí toho API callu se zadáním registryId (s hodnotou našeho aws účtu, tedy `registryIds=[147946154733]`) by user mohl uploadovat do kterékoli repository pod naším aws účtem. Pokud tomu chceme zabránit, tak musíme buď vytvořit zvláštní aws account pro každýho vendora, nebo to řešit přes IAM.

**Comment by ondrejhlavacek** [comment]
No tak to maj teda velezmatek v terminologii! Pardon! Plus mě tam mate `default registry`. A zbytek toho vůbec nechápu - je jako možný mít víc AWS accountů k jedné registry pod jedním loginem?

AWS account pro vendory určitě dělat nechcem, ale bude potřeba dělat IAM usery? V těch pak taky nastane zmatek :-/

**Comment by JakubMatejka** [comment]
No to jo, taky mi to chvíli trvalo. ;o) To není víc aws accountů k jedný registry, ale že vygeneruješ token, který bude fungovat pro víc registrů (tj. víc aws accountů) současně. A půjde to definovat, hádám, díky nějakýmu tomu cross-account accessu. K čemu to je dobrý ale moc nevim. ;o) 

User není třeba, vytvářím roli pro každou appku. AFAIK to jinak nejde. Podle dokumentace ten token právě na repozitář omezit nejde, takže zbývá jen IAM. A v něm žádnou "inline" roli neudělám, takže ji musím nejdřív vyrobit. Inspiroval jsem se tady: http://blog.shippable.com/setting-permissions-on-aws-ec2-ecr-repositories (jen místo userů dělám ty role)

**Comment by JakubMatejka** [comment]
I z toho jak to popisují v dokumentaci vyplývá, že máme používat iam policy: http://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicies.html

**Comment by ondrejhlavacek** [comment]
Takže jeden registr bude mít roli pro push a jednu pro pull a k těm se budou generovat dočasný credentials?

**Comment by JakubMatejka** [comment]
No to jsem se právě ptal jestli je třeba rozlišovat jednu roli na push a druhou na pull. Uživatel sám asi právo na pull mít může, ne?

**Comment by Halama** [comment]
Myslím že by tomu mohla stačit jedna role pro plný přístup k ECR. A pro generování credentials by se použilo http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html kde by se pomocí policy upřesnilo do kterého repozitáře to bude mít přístup. A pomocí vrácených credentials by se zavolal a vrátil ten `ecr login`

**Comment by Halama** [comment]
chctelo by to ale prvni vyzkouset jestli tam nejaky zadrhel nez by se to zaclo davat do appky. Nemel by to byt problem treba pomoci php sdk si to vyzkouset.

**Comment by JakubMatejka** [comment]
Tvl. jak to děláš? Já jsem v tý dokumentaci neúspešně hledal určitě víc než hodinu jestli jde assumnout dynamicky vytvořenou roli. ;o)

**Comment by Halama** [comment]
tohle zrovna pouzivame na generovani pristup v sapi (teda ne assume role ale get federation token) tak to mam celkem proslapnuty. Tady u toho assume role si ale teda porad nejsem uplne jistej.

**Comment by JakubMatejka** [comment]
Aha, tak to jsem viděl v js sdk (http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#assumeRole-property). Jenže mě tam zmátl ten povinnej parametr `RoleArn`, resp. když jsem ho viděl, tak už jsem si nevšiml toho `Policy` parametru. Takže do `RoleArn` se dá ta role s full přístupem a v `Policy` se omezí na repository? To by nejspíš mělo jít

**Comment by Halama** [comment]
jj presne tak si to predstavuju, do toho RoleArn da roli která bude mít full access do ECR a tou policy se to pak ořízne. 

První bych to asi vyzkoušel mimo tu lambdu s nějakýma user credentials a pak to zkusil jestli to bude šlapat i z rolí. V nejhorsim pokud to bude vubec fungovat by se i do te lambdy daly injectnout user credentials které by volali to assume role.

**Comment by Halama** [comment]
kazdopadne to opravneni toho ECR je vyreseny teda hodne podivne, nechapu proc tomu get login nedali proste moznost to omezit na repository :(

**Comment by Halama** [comment]
omg, ted jsem googlil a koukam ze uz jsi to resil :) http://forum.serverless.com/t/is-it-possible-to-assume-a-role-from-a-lambda-function/976

**Comment by JakubMatejka** [comment]
jj. ale zatím mi nikdo neporadil (a nejspíš už ani neporadí ;o/ )

**Comment by Halama** [comment]
kdyztak se tam pro to daji ty staticky credentials pokud to vubec bude slapat.
