### ISSUE TITLE
Add missing environment variables to make scripts and README

### ISSUE THREAD

**Issue by pmuens** [keboola/developer-portal#43]
When running the setup steps in the `README.md` file I get an error that the `ACCOUNT_ID` and the `COGNITO_POOL_ID` is missing in `./env.yml`.

Adding those environment variables manually resolved the issue...

**Comment by JakubMatejka** [comment]
Did you run the installation using `make` command? It gets and saves `ACCOUNT_ID` automatically using `node scripts/setup.js save-account-id` and `COGNITO_POOL_ID` using `node scripts/setup.js create-cognito`

**Comment by JakubMatejka** [comment]
I will close the issue because the installation quite changed and it should be fixed for sure by now. Me and my colleagues tried it several times since then and it works ok. Anyway thank you very much for trying of the process and reporting.
