### ISSUE TITLE
Updating app's vendor keeps app under original vendor

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#51]
1. register app under your account (e.g. `keboola` vendor
2. update app's vendor using "update app as admin" call

^vendor is changed (also available in response), but app's id remains with old prefix.

**Comment by ujovlado** [comment]
Mozno by stacilo, keby sa dal vendor (vratane id) zmenit pokial nie je aplikacia approved.

**Comment by JakubMatejka** [comment]
Fixnuto přidáním admin API callu na vytvoření aplikace u kterýho se vybírá vendor
