### ISSUE TITLE
Internal launch

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#55]
Developer portal se pomalu blíží resp. už v produkci je tak bych a napadá mě k tomu pár věcí které bysme měli dotáhnout:

- [x] "školení" - ukázat všem developerům v Keboola jak to funguje a k čemu to je, jak s tím spolupracuje KBC.
- [x] troubleshooting pro dohled. Asi postupně sepisovat nějaké tipy sem https://github.com/keboola/developer-portal
- [x] Všchni keboola dev by měli mít založený admin účet
- [x] Popsat jak spravovat komponenty/aktualizovat https://sites.google.com/a/keboola.com/devel/kbc/docker 
- [ ] V téhle fázi je potřeba komponenty evidovat v connection.keboola.com i developer portalu. Mělo by se to dát vědět všem. A vymyslet kdy udělat ten switch kdy i connection.keboola.com začne tahat komponenty z developer portalu, což je krok kterého se trochu bojím a bylo by super kdybysme to nějak dokázali zapnout třeba pro určité projekty, což by znamenalo nějakou upravu v KBC a asi i docker bundle ale za tu práci to imho stojí.
- [ ] Chyby z dev-portalu by měly chodit do #support_maintenance

**Comment by odinuv** [comment]
ja uz zase nevim, proc bude potreba zadavat komponenty na obe mista, to bude strasny

**Comment by Halama** [comment]
to by melo trvat jen chvili, jinak nevim jak to otestovat.

**Comment by Halama** [comment]
zatim se to ale tak nedeje, takze se udela nejaky diff command podle ktereho se to pak doklika do developer portalu to co se od posledniho syncu zmenilo v kbc. Automaticky sync uz delat nebudeme.

**Comment by JakubMatejka** [comment]
Popsal/rozšířil jsem pár věcí ve wiki:
- https://github.com/keboola/developer-portal/wiki/Troubleshooting
- https://github.com/keboola/developer-portal/wiki/App-Flow
- https://github.com/keboola/developer-portal/wiki/User-Flow

**Comment by JakubMatejka** [comment]
Co se týče chyb, chodí to do #developer-portal-ntf. Můžu to přesměrovat do #support_maintenance, ale do stejnýho kanálu chodí i requesty na approval userů a aplikací. Což vlastně asi nemusí vadit? Nebo to můžu upravit tak, že se bude zvlášť zadávat kanál pro chyby a zvlášť pro notifikace adminům.

**Comment by JakubMatejka** [comment]
Aktualizoval jsem Sites, resp. jsem to původní zkopíroval a upravil tady: https://sites.google.com/a/keboola.com/devel/kbc/docker/docker-with-developer-portal

**Comment by JakubMatejka** [comment]
@Halama ty jsi někde psal, že se mezi komponentama v us kbc a developer portálem udělá nějaký diff, podle kterýho se poslední změny dopíšou do portálu manuálně. Měl jsi na mysli nějaký konkrétní řešení, nebo je to třeba teprve vymyslet a napsat?

**Comment by Halama** [comment]
zatim to neni domysleny. Prijde mi ze by mohl byt skript ktery stahne https://connection.keboola.com/v2/storage pak se pripoji na developer portal a prozene aktualni nastaveni https://github.com/keboola/connection/blob/master/application/modules/storage/cli-commands/SyncComponents.php a pak to porovna. V moment kdy to bude 100% sedet bysme prepnuli connection.keboola.com at se syncuje z dev portalem.

**Comment by JakubMatejka** [comment]
Myslím, že můžeme zavřít, zybtek v #69
