### ISSUE TITLE
Encrypt sensitive config values with KMS

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/developer-portal#57]
see https://github.com/marcy-terui/serverless-crypt

**Comment by odinuv** [comment]
co se tim bude encryptovat?

**Comment by JakubMatejka** [comment]
Přemýšlel jsem zejména nad heslem k rds. Nicméně vlastně nevím jestli je to vůbec třeba. Konfigurák se přibalí ke kódu lambda funkcí, pošle se do s3 a odtamtud se deployne do lambdy. Ty env proměnný jsou pak vidět třeba v konzoli: 

<img width="1128" alt="lambda_management_console" src="https://cloud.githubusercontent.com/assets/215660/22017818/1fb7e860-dcac-11e6-9aac-15ae4598eae6.png">

Ale ta je koneckonců pod https, tak to asi ani není potřeba(?)

**Comment by odinuv** [comment]
Aha, myslel jsem, ze jde o konfigurace komponent. No, kdyz se nedko dostane do AWS konzole, tak se k tomu heslu k RDS dostane tak jako tak, ne?

**Comment by JakubMatejka** [comment]
No právě ;o)

**Comment by Halama** [comment]
heslo do db sifrovat potreba neni, staci kdyz to lezi v S3 a vni je to zasifrovane
