### ISSUE TITLE
Sync components issues

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#69]
Tady je skript který vrací rozdíli mezi stacky:
 - https://connection.keboola.com/v2/storage
 - https://connection-sync-test.devel.keboola.com/components-compare - je nastavený tak jak bude nastavené connection.keboola.com po prepnutí na sync z dev portalem.

To bude možné udělat až to nebude hlásit žádné rozdíly. 
- [x] Review poprovnávacího skriptu https://github.com/keboola/components-compare/blob/master/compare.js
- [x] Doregistrovat komponenty které chybí.
- [x] Aktalizovat ty kde jsou nějaké změny (operace `update`)

### V KBC nenastaveno v dev-portalu nastaveno
Z dev portálu se synchronizovala hodnota, v aktuální verzi connection.keboola.com není nastavena (fallback na default).
```
{
      "component": "bizztreat.ex-fedger",
      "diff": {
        "/data/network": {
          "operation": "delete"
        },
        "/data/staging_storage": {
          "operation": "delete"
        }
      }
   }
```
Tohle je případ kdy v connection.keboola.com není pro komponentu `network` nastaveno a z dev portalu je syncnuté `"network": "bridge",`.

Týká se atributů:
 - `data.network`
 - `data.staging_storage`
 - `data.definition.tag` - `latest` vs. nenastaven `fisa.ex-typeform`
 - `configuration_format` - `json` vs. nenastaven `keboola.processor.iconv`
 
Co s tím? Upravit porovnávácí skript tak že pokud je atribut označen jako `delete` tak ověří že má pro daný atribut správnou default hodnotu?

### V KBC nastaveno v dev-portalu nenastaveno
Opačný případ kdy v KBC je nastvena defaultní hodnota a po syncu není atribut přítomný vůbec tím pádem fallback na default.

```{
      "component": "bizztreat.ex-firebase",
      "diff": {
        "/data/staging_storage": {
          "operation": "delete"
        },
        "/data/forward_token": {
          "operation": "add",
          "value": false
        }
      }
    },
```
Tohle je případ kdy v connection.keboola.com je `"forward_token": false` a po syncu z dev portalu není nastavené.

Týká se atributů: 
 - `data.forward_token` -  `"forward_token": false,` v kbc
 - `data.default_bucket` - `"default_bucket": false,`
 - `forward_token_details` - `"forward_token_details": false,`
 -  `data.cpu_shares` - `"cpu_shares": 1024,` - `eboola.ex-db-mssql`

Jak fixnout? Ty hodnoty které mají default `false` je možné nastavit v sync skriptu v kbc. CpuShares je možný tam kde chybí nastavit v dev portalu.

### Komponenty receptů
Nesyncují se jim data. Používají se ještě? Např. `rcp-anomaly`

**Comment by ondrejhlavacek** [comment]
ad **V KBC nenastaveno v dev-portalu nastaveno** - imho stačí zkontrolovat, že to nastavilo defaulty, ty jsou vidět tady https://github.com/keboola/docker-bundle/blob/master/Docker/Configuration/Component.php a nebudou se jen tak měnit

ad **V KBC nastaveno v dev-portalu nenastaveno** pokud jde o nepovinné atributy s defaultní hodnotou, tak bych se tím zase klidně nezabýval. 

klidně se to může celý nastavit tak, že to všechny nepovinný parametry, ve který jsou defaultní hodnoty, vymaže, pokud výstup bude přehlednější a čitelnější

**Comment by ondrejhlavacek** [comment]
můžu připravit json schéma té konfigurace, oproti které se to může validovat a normalizovat a pak by se mohly porovnávat až ty normalizovaný data

**Comment by Halama** [comment]
tak to muzes asi doplnit do toho skriptu, ja uz se v tom ztracim,.

**Comment by ondrejhlavacek** [comment]
to bohužel ne... jsem teď zahrabanej v bigquery writeru, ale schéma bych asi stihl operativně vysmrknout. mám se do toho pustit?

**Comment by Halama** [comment]
bavili jsme se o tom ted s najlosem udelam to tou variantou kdy pri syncu z dev portalu nastavim i ty false default hodnoty. Tim se sjednoti pripad 2 a pro prvni pripad kdy to v KBC nastavene neni a v dev-portal jo zkontroluju pro dane pole jestli jde o default.

**Comment by Halama** [comment]
Uprava na strane synchronizace pro prvni pripad https://github.com/keboola/connection/commit/447f6de76347cc8cb4376d2609a7421244edc979

**Comment by Halama** [comment]
Do porovnavaciho skriptu jsem přidal normalizaci na defaultni hodnoty https://github.com/keboola/components-compare/commit/e1d7c458847731052184810f013ddd5e2f486de8#diff-b217163d10a7ee6ffdb5baaa63288b92R69

Po spuštění už to vypadá o poznání lépe https://connection-sync-test.devel.keboola.com/components-compare

**Comment by Halama** [comment]
@odinuv Co ty komponenty které začínají `rcp-` a mají v datech nějaké divné věci. Používá se to? nebo se můžou smazat?

**Comment by Halama** [comment]
Tak jsem to ponastavoval to co nesedela a krome tech `rcp-` komponent a par asi testovacich to vypada ok https://connection-sync-test.devel.keboola.com/components-compare

Tohle jsou ty testovaci, ty by mely jit pryc resp. jejich data by mely jit pryc, je to problem?
![image](https://cloud.githubusercontent.com/assets/903531/23168523/bd605360-f848-11e6-8a4f-8d0361694dc2.png)

**Comment by JakubMatejka** [comment]
A keboola.docker-log-test se podle odina může smazat (https://keboola.slack.com/archives/docker-runner/p1487162891000009)

**Comment by Halama** [comment]
jo tak ten zpětnej sync tech rcp jsem rozbil behem uprav ktere jsem tam delal :)

**Comment by Halama** [comment]
jdu to fixnout

**Comment by Halama** [comment]
sync receptu snad fixnutej https://github.com/keboola/connection/commit/c812af39fdd9971decd4df6d46e69beb7c5bf7b0

**Comment by odinuv** [comment]
sice pozde ale prece: jo, recepty se pouzivaji (ne moc, ale pouzivaji), takze by tam mely zustat. Nicmene uz se asi nebudou nijak menit

**Comment by Halama** [comment]
jo v pohode s temi recepty uz se to vysvetlilo, budou tam. dik

**Comment by Halama** [comment]
Fix syncu receptu byl nasazen. Ted uz to vypada ze je vse vyreseno:

https://connection-sync-test.devel.keboola.com/components-compare

![image](https://cloud.githubusercontent.com/assets/903531/23176373/f30884be-f862-11e6-8e43-378553ec2e4a.png)

**Comment by Halama** [comment]
hotovo, syncnuto
