### ISSUE TITLE
Short description should be required

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#70]
Component `test.test-app` with shortDescription set `null`, caused broken UI in EU.

**Comment by JakubMatejka** [comment]
Short description se společně s dalšími kontroluje až při žádosti o approval (https://github.com/keboola/developer-portal/blob/master/lib/app.js#L15). To nestačí?

**Comment by JakubMatejka** [comment]
UI by to rozbíjet nemělo, protože neschválený aplikace v něm nemají být. Pokud tam nějakou vidíš, tak by se asi mělo short description doplnit, nebo ji nastavit na neschválenou.

**Comment by Halama** [comment]
tahle appka to rozbila i tak. Ona sice není public ale ui s tím pracuje.

**Comment by Halama** [comment]
koukam za schvalena ale neni tak nevim jak se tam dostala.

**Comment by Halama** [comment]
sakra a ted jsem ji omylem prejmenoval:)

**Comment by Halama** [comment]
Možná teda do toho skriptu který syncuje komponenty přidat vynechání komponenty která není schválená?

![image](https://cloud.githubusercontent.com/assets/903531/23165245/691dbd7c-f83b-11e6-8588-84fd7eb6fa41.png)

**Comment by Halama** [comment]
Asi bych to tam přidal a tím pádem tohle issue zavřel, ok?

**Comment by JakubMatejka** [comment]
Těm co mají `isApproved=false` se nastavuje flag `excludeFromNewList`. Aha, takže v tom listu v KBC vlastně zůstávají. (ale nově to nebude, protože nepůjde nastavit `isPublic=true` dokud nebude appka approvenutá).

**Comment by Halama** [comment]
jo ale ono je jedno jestli ma `excludeFromNewList` nebo ne, i tak s tim ui pracuje.

**Comment by Halama** [comment]
takže by to imho komponenty který nejsou schválený vůbec nemělo syncovat, pak ale zas nepůjde otestovat. tak nevím.

**Comment by Halama** [comment]
nebo to fixnu vlastně v kbc ať to vrací vždy description jako string.
