### ISSUE TITLE
RDS  - settings

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#73]
RDS by mělo být v privátním subnetu do kterého budou mít přístup pouze lambda funkce.
Přístup zvenčí přes bastion ssh instanci.

**Comment by JakubMatejka** [comment]
Bude třeba myslet na to, aby fungoval:
- [ ] init databáze
- [ ] migrace

Jinak já vůbec nevím jak na to. ;o) ec2 instanci bych asi ještě do CF templaty přidal, ale to je tak skoro všechno.

**Comment by Halama** [comment]
jj s tim pocitam. Init db a migrace se v necem lisi?
Jinak predpokladam ze nebude problem to spojeni do db udelat pres ssh proxy, porad to ale znamena mit tam otevreny ssh pristup.

Jeste prozkoumam jestli by to neslo jinak, napr. v SAPI se migrace spousti v ECS kontejneru. Tak jestli by se tady nemohla spustit v lambde nebo tak.

**Comment by JakubMatejka** [comment]
Lambda funkci bych na migrace vlastně napsat mohl. A init vlastně už ani nejspíš potřeba nebude. Původně byl import z kbc součást instalace, ale to už se nedělá. Tak vlastně stačí ta ec2 jen na servisní přístup pokud by tam bylo třeba něco kontrolovat napřímo

**Comment by Halama** [comment]
Hledam ten serverless db-migrate plugin ktery pouzivas jestli tomu pujde podstrcit SSH proxy.
U te migrace v lambda funkci se trochu bojim toho ze migrace obcas muze trvat dele nez je limit behu lambda funkce. I kdyz v pripade dev-portalu to asi zatim neni issue, co myslis?

**Comment by JakubMatejka** [comment]
Ten plugin je tady: https://github.com/keboola/developer-portal/blob/master/.serverless_plugins/db-migration.js Jinak je to tahle knihovna: https://db-migrate.readthedocs.io/en/latest/ No to je pravda, zatím to trvá jednu dvě vteřiny, ale časem to může docela narůst. Tak teď teda nevím ;o)

**Comment by Halama** [comment]
zajimalo by me jestli to nekdo resi pres lambdu nevis? jestli to treba nekde v serverless doporucuji nebo se o tom zminuji? 
Pres tu lambdu by to bylo super ze by v travisu nemusel byt klic na to ssh a celkove bysme to ssh mohli zariznout jeste vic.

**Comment by Halama** [comment]
jinak jsem tam nasel https://github.com/db-migrate/node-db-migrate/blob/68de8447b33a410b461e7fb13c1ef22ac004dc95/test/driver/index_test.js a podle toho to vypada ze to umi SSH tunnel, asi to vyzkousim.
