### ISSUE TITLE
Run db migrations in Lambda

### ISSUE THREAD

**Issue by Halama** [keboola/developer-portal#76]
Přeci jenom si myslím že by to bylo lepší, nemuseli bysme vůbec řešit SSH přístup travisu apod. A ssh by zůstalo jenom pro naši možnost manuálně zasáhnout do db.

**Comment by JakubMatejka** [comment]
Ok, jasně. Timeout jde per-function nastavit až na 300 s, to by snad mělo stačit. Mám se do toho pustit? Za chvíli dodělám jednu věc, tak budu volnej.

**Comment by Halama** [comment]
jo to by bylo super kdyby ses do toho mohl pustit.

**Comment by JakubMatejka** [comment]
Mno, lambda funkce by fungovala s jedním problémem, že migrace o tom co dělá píše jen do konzole (tj. do Cloudwatche) a nevím moc jak to z ní inteligentně dostat tak, aby to bylo vidět v outputu deploye.

Při deployi mi to ale zatím nechce moc fungovat, budu pokračovat zítra.

**Comment by Halama** [comment]
to asi zas tolik nevadí. U KBC to je stejně že output migrace jde do PT a v logu deploye jde vidět jenom že něco dělá.

![image](https://cloud.githubusercontent.com/assets/903531/23267624/996cf716-f9eb-11e6-8710-37df9c7a0518.png)
