### ISSUE TITLE
Tune icon resizing.

### ISSUE THREAD

**Issue by ujovlado** [keboola/developer-portal#93]
I uploaded transparent PNG:

![1](https://cloud.githubusercontent.com/assets/419849/24105979/ee79ff8e-0d86-11e7-81e8-2928245d4c27.png)

And its 32px version is a a bit strange (probably affects also 64px version when bigger img is uploaded) :

![5](https://cloud.githubusercontent.com/assets/419849/24106142/4ba26d90-0d87-11e7-9465-c8c530870b28.png)

Expected result:

![1-32](https://cloud.githubusercontent.com/assets/419849/24106154/59d43218-0d87-11e7-90aa-000ac1b41809.png)

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/developer-portal/releases/tag/2.3.2
