### ISSUE TITLE
generic extractor based components

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/developer-portal#94]
update all to ECR repository

**Comment by Halama** [comment]
Mělo by mít stejné nastavení jako https://apps.keboola.com/apps/keboola/ex-generic-v2

**Comment by JakubMatejka** [comment]
To je pořád aktuální problém?

**Comment by Halama** [comment]
pořeším to ted v rámci toho přepínání na ECR, do integrace genericu dám asi update všech komponent na něm postavených.

**Comment by Halama** [comment]
Blbý je že ty klony jsou na sterém genericu který má konfiguraci v `yaml` přemýšlím jak to přepnout. A nejjednoduší mi přijde dát to jako parametr do toho cli pro update appky.

**Comment by odinuv** [comment]
cemu to vadi? pokud zaraz zaktualizujes image i typ konfgurace tak se nic nedeje

**Comment by Halama** [comment]
jo ale to cli to neumelo tak jsem na to ted poslal PR. Rucne to u 17 komponent delat nebudu:)

**Comment by Halama** [comment]
a chci je vsechny ty komponenty soupnout do deploy tohodle repa.

**Comment by Halama** [comment]
nahodil jsem deploy genericu přes dev portal a update jeho tagu https://travis-ci.org/keboola/generic-extractor/builds/264727809
zatim bez komponent na nem postavenych

**Comment by Halama** [comment]
Zatím jsem tam hodil jenom github extraktor https://github.com/keboola/generic-extractor/commit/cf81c76689ba7151315ae83eab992a3ec88508aa a vyzkoušel že běží https://connection.keboola.com/admin/projects/2703/jobs/308737335 .
Pokud je to takhle ok dodal bych tam zítra zbylých 25 (wtf) extractorů používající image genericu.

**Comment by Halama** [comment]
Už se updatují i ostatní templatované komponenty https://github.com/keboola/generic-extractor/commit/04041cfb4d4136e4978c7a4feadf5bbc4466b928
