### ISSUE TITLE
Deprecated flag

### ISSUE THREAD

**Issue by MiroCillik** [keboola/developer-portal#98]
Pridat k apkam `deprecated` flag zaroven s expiration date a odkazom na novu verzi komponenty. 
CRON bude checkovat expiration date deprekovanych komponent. 
Tyzden pred vyprsanim upozorni uzivatelov mailom, ze sa komponenta vypne a ze maju zmigrovat na novu verziu.

Deprecated apka sa nezobrazi v zozname novych konfiguraci.
Na overview sa bude zobrazovat upozornenie, ze je komponenta deprekovana a treba ju zmigrovat na novu verziu.

Komponenta sa moze oznacit ako deprecated, az ked existuje nova verzia komponenty a idealne aj migracny tool.

**Comment by JakubMatejka** [comment]
Část v dev portálu je hotová
